// ลิขสิทธิ์และจัดทำโดย ธนพงศ์ ชูแก้ว (Copyright © Thanaphong Chukaew. All rights reserved.)

// Skill pool. classOnly: null = shared by all classes, otherwise restricted to that class id.
// kind: 'attack' | 'heal' | 'buffSelf' | 'debuffEnemy'
// target: 'singleEnemy' | 'allEnemies' | 'self'
(function () {
  var skills = [
    // --- basic ---
    { id: 'attack', name: 'โจมตี', nameEn: 'Attack', element: 'phys', kind: 'attack', power: 1.0, cost: 0, target: 'singleEnemy', minLevel: 1, classOnly: null, icon: 'swordAttack', desc: 'โจมตีกายภาพพื้นฐาน ไม่เสีย MP', descEn: 'Basic physical attack. Costs no MP.' },

    // --- shared single-target nukes ---
    { id: 'fire_bolt', name: 'ลูกไฟ', nameEn: 'Fireball', element: 'fire', kind: 'attack', power: 1.5, cost: 6, target: 'singleEnemy', minLevel: 1, classOnly: null, icon: 'fire', desc: 'พลังไฟใส่ศัตรูเดี่ยว', descEn: 'Fire damage to a single enemy.' },
    { id: 'ice_shard', name: 'เศษน้ำแข็ง', nameEn: 'Ice Shard', element: 'ice', kind: 'attack', power: 1.5, cost: 6, target: 'singleEnemy', minLevel: 1, classOnly: null, icon: 'ice', desc: 'เศษน้ำแข็งแหลมคมใส่ศัตรูเดี่ยว', descEn: 'A sharp ice shard hits a single enemy.' },
    { id: 'spark', name: 'สายฟ้าฟาด', nameEn: 'Spark Strike', element: 'elec', kind: 'attack', power: 1.6, cost: 7, target: 'singleEnemy', minLevel: 3, classOnly: null, icon: 'elec', desc: 'สายฟ้าฟาดใส่ศัตรูเดี่ยว', descEn: 'A lightning bolt strikes a single enemy.' },
    { id: 'gale_cut', name: 'คมลม', nameEn: 'Gale Cut', element: 'wind', kind: 'attack', power: 1.6, cost: 7, target: 'singleEnemy', minLevel: 3, classOnly: null, icon: 'wind', desc: 'คมลมกรีดใส่ศัตรูเดี่ยว', descEn: 'A blade of wind slices a single enemy.' },
    { id: 'holy_ray', name: 'แสงศักดิ์สิทธิ์', nameEn: 'Holy Ray', element: 'light', kind: 'attack', power: 1.7, cost: 9, target: 'singleEnemy', minLevel: 6, classOnly: null, icon: 'light', desc: 'ลำแสงศักดิ์สิทธิ์เจาะทะลุศัตรู', descEn: 'A holy beam pierces through the enemy.' },
    { id: 'shadow_bite', name: 'เขี้ยวเงามืด', nameEn: 'Shadow Fang', element: 'dark', kind: 'attack', power: 1.7, cost: 9, target: 'singleEnemy', minLevel: 6, classOnly: null, icon: 'dark', desc: 'เขี้ยวเงามืดกัดกินศัตรู', descEn: 'Fangs of shadow tear into the enemy.' },
    { id: 'almighty_burst', name: 'มหาประลัย', nameEn: 'Almighty Burst', element: 'almighty', kind: 'attack', power: 1.8, cost: 14, target: 'singleEnemy', minLevel: 10, classOnly: null, icon: 'almighty', desc: 'พลังบริสุทธิ์ ไม่มีศัตรูตัวใดต้านทานได้', descEn: 'Pure power that no enemy can resist.' },

    // --- shared AoE ---
    { id: 'inferno', name: 'พายุเพลิง', nameEn: 'Inferno', element: 'fire', kind: 'attack', power: 1.1, cost: 14, target: 'allEnemies', minLevel: 8, classOnly: null, icon: 'fire', desc: 'เพลิงกวาดล้างศัตรูทั้งหมด', descEn: 'Flames sweep across all enemies.' },
    { id: 'blizzard', name: 'พายุหิมะ', nameEn: 'Blizzard', element: 'ice', kind: 'attack', power: 1.1, cost: 14, target: 'allEnemies', minLevel: 8, classOnly: null, icon: 'ice', desc: 'หิมะกวาดล้างศัตรูทั้งหมด', descEn: 'A blizzard sweeps across all enemies.' },
    { id: 'thunderstorm', name: 'พายุสายฟ้า', nameEn: 'Thunderstorm', element: 'elec', kind: 'attack', power: 1.2, cost: 16, target: 'allEnemies', minLevel: 12, classOnly: null, icon: 'elec', desc: 'สายฟ้ากระหน่ำศัตรูทั้งหมด', descEn: 'Lightning pounds all enemies.' },
    { id: 'tempest', name: 'พายุหมุน', nameEn: 'Tempest', element: 'wind', kind: 'attack', power: 1.2, cost: 16, target: 'allEnemies', minLevel: 12, classOnly: null, icon: 'wind', desc: 'พายุหมุนโหมกระหน่ำศัตรูทั้งหมด', descEn: 'A raging whirlwind batters all enemies.' },
    { id: 'radiant_wave', name: 'คลื่นรัศมี', nameEn: 'Radiant Wave', element: 'light', kind: 'attack', power: 1.2, cost: 18, target: 'allEnemies', minLevel: 15, classOnly: null, icon: 'light', desc: 'คลื่นแสงชำระล้างศัตรูทั้งหมด', descEn: 'A wave of light purges all enemies.' },
    { id: 'abyss_wave', name: 'คลื่นนรก', nameEn: 'Abyssal Wave', element: 'dark', kind: 'attack', power: 1.2, cost: 18, target: 'allEnemies', minLevel: 15, classOnly: null, icon: 'dark', desc: 'คลื่นความมืดกลืนกินศัตรูทั้งหมด', descEn: 'A wave of darkness consumes all enemies.' },

    // --- heal / buff / debuff ---
    { id: 'heal', name: 'ฟื้นฟู', nameEn: 'Heal', element: 'light', kind: 'heal', power: 0.38, cost: 8, target: 'self', minLevel: 1, classOnly: null, icon: 'heart', desc: 'ฟื้นฟู HP ราว 38% ของ HP สูงสุด', descEn: 'Restores about 38% of max HP.' },
    { id: 'greater_heal', name: 'ฟื้นฟูขั้นสูง', nameEn: 'Greater Heal', element: 'light', kind: 'heal', power: 0.7, cost: 16, target: 'self', minLevel: 9, classOnly: null, icon: 'heart', desc: 'ฟื้นฟู HP ราว 70% ของ HP สูงสุด', descEn: 'Restores about 70% of max HP.' },
    { id: 'focus', name: 'สมาธิรบ', nameEn: 'Battle Focus', element: 'phys', kind: 'buffSelf', stat: 'atkmag', amount: 0.25, cost: 6, target: 'self', minLevel: 4, classOnly: null, icon: 'buffUp', desc: 'เพิ่มพลังโจมตี/เวท 25% ใน 3 เทิร์น', descEn: 'Boosts ATK/MAG by 25% for 3 turns.' },
    { id: 'iron_stance', name: 'ท่ายืนเหล็ก', nameEn: 'Iron Stance', element: 'phys', kind: 'buffSelf', stat: 'defres', amount: 0.3, cost: 6, target: 'self', minLevel: 4, classOnly: null, icon: 'shieldGuard', desc: 'เพิ่มการป้องกัน/ต้านเวท 30% ใน 3 เทิร์น', descEn: 'Boosts DEF/RES by 30% for 3 turns.' },
    { id: 'guard_break', name: 'ทลายเกราะ', nameEn: 'Guard Break', element: 'phys', kind: 'debuffEnemy', stat: 'def', amount: 0.3, cost: 5, target: 'singleEnemy', minLevel: 5, classOnly: null, icon: 'debuffDown', desc: 'ลดการป้องกันศัตรูเดี่ยว 30% ใน 3 เทิร์น', descEn: 'Lowers a single enemy DEF by 30% for 3 turns.' },
    { id: 'haste', name: 'เร่งความเร็ว', nameEn: 'Haste', element: 'wind', kind: 'buffSelf', stat: 'spd', amount: 0.4, cost: 8, target: 'self', minLevel: 7, classOnly: null, icon: 'buffUp', desc: 'เพิ่มความเร็ว 40% ใน 3 เทิร์น', descEn: 'Boosts SPD by 40% for 3 turns.' },

    // --- Blade Knight signatures ---
    { id: 'cross_slash', name: 'กากบาทสังหาร', nameEn: 'Cross Slash', element: 'phys', kind: 'attack', power: 2.0, cost: 10, target: 'singleEnemy', minLevel: 1, classOnly: 'blade', icon: 'blade', desc: 'ฟันไขว้พลังสูงใส่ศัตรูเดี่ยว', descEn: 'A powerful crossing slash hits a single enemy.' },
    { id: 'armor_piercer', name: 'ทะลวงเกราะ', nameEn: 'Armor Piercer', element: 'almighty', kind: 'attack', power: 1.8, cost: 9, target: 'singleEnemy', minLevel: 6, classOnly: 'blade', icon: 'swordAttack', desc: 'แทงทะลุจุดอ่อนของเกราะศัตรู ด้วยแรงบริสุทธิ์ที่ไม่มีสิ่งใดต้านทานได้', descEn: "Thrusts through a gap in the enemy's armor with raw force nothing can resist." },
    { id: 'blade_dance', name: 'ระบำคมดาบ', nameEn: 'Blade Dance', element: 'phys', kind: 'attack', power: 1.3, cost: 16, target: 'allEnemies', minLevel: 10, classOnly: 'blade', icon: 'blade', desc: 'หมุนดาบฟาดฟันศัตรูทั้งหมด', descEn: 'A spinning blade strikes all enemies.' },
    { id: 'warriors_wrath', name: 'โกรธเกรี้ยวนักรบ', nameEn: "Warrior's Wrath", element: 'phys', kind: 'buffSelf', stat: 'atk', amount: 0.35, cost: 10, target: 'self', minLevel: 13, classOnly: 'blade', icon: 'buffUp', desc: 'เพิ่มพลังโจมตี 35% ใน 3 เทิร์น', descEn: 'Boosts ATK by 35% for 3 turns.' },
    { id: 'end_bringer', name: 'ดาบอวสาน', nameEn: 'End Bringer', element: 'phys', kind: 'attack', power: 2.6, cost: 18, target: 'singleEnemy', minLevel: 18, classOnly: 'blade', icon: 'blade', desc: 'ท่าไม้ตายที่ทุ่มพลังทั้งหมดลงในดาบเดียว', descEn: 'A finishing blow that pours everything into a single strike.' },
    { id: 'guard_sunder', name: 'ทลายเกราะป้องกัน', nameEn: 'Guard Sunder', element: 'phys', kind: 'debuffEnemy', stat: 'def', amount: 0.2, cost: 5, target: 'singleEnemy', minLevel: 3, classOnly: 'blade', icon: 'debuffDown', desc: 'ฟันเจาะเกราะศัตรูเดี่ยว ลดการป้องกัน 20% ใน 3 เทิร์น', descEn: "Cracks a single enemy's guard, lowering DEF by 20% for 3 turns." },
    { id: 'blademasters_flourish', name: 'ลีลาจอมคมดาบ', nameEn: "Blademaster's Flourish", element: 'phys', kind: 'attack', power: 2.2, cost: 14, target: 'singleEnemy', minLevel: 15, classOnly: 'blade', icon: 'swordAttack', desc: 'ท่วงท่าดาบที่ผ่านการฝึกฝนจนเชี่ยวชาญ ฟันใส่ศัตรูเดี่ยว', descEn: 'A masterfully honed sword flourish strikes a single enemy.' },

    // --- Elementalist signatures ---
    { id: 'twin_elements', name: 'พลังคู่ธาตุ', nameEn: 'Twin Elements', element: 'fire', kind: 'attack', power: 1.5, cost: 12, target: 'singleEnemy', minLevel: 1, classOnly: 'elementalist', icon: 'sparkles', desc: 'ปล่อยธาตุสุ่ม (ไฟ/น้ำแข็ง/ฟ้า/ลม) สองครั้งใส่ศัตรูเดี่ยว', descEn: 'Unleashes a random element (fire/ice/lightning/wind) twice on a single enemy.', randomElement: ['fire', 'ice', 'elec', 'wind'], hits: 2 },
    { id: 'elemental_seal', name: 'ผนึกธาตุ', nameEn: 'Elemental Seal', element: 'ice', kind: 'debuffEnemy', stat: 'res', amount: 0.25, cost: 8, target: 'singleEnemy', minLevel: 5, classOnly: 'elementalist', icon: 'debuffDown', desc: 'ลดต้านเวทศัตรูเดี่ยว 25% ใน 3 เทิร์น', descEn: 'Lowers a single enemy RES by 25% for 3 turns.' },
    { id: 'elemental_sovereignty', name: 'ราชันธาตุ', nameEn: 'Elemental Sovereignty', element: 'fire', kind: 'buffSelf', stat: 'mag', amount: 0.3, cost: 9, target: 'self', minLevel: 9, classOnly: 'elementalist', icon: 'buffUp', desc: 'เพิ่มพลังเวท 30% ใน 3 เทิร์น', descEn: 'Boosts MAG by 30% for 3 turns.' },
    { id: 'grand_cataclysm', name: 'มหาวิบัติ', nameEn: 'Grand Cataclysm', element: 'almighty', kind: 'attack', power: 1.4, cost: 22, target: 'allEnemies', minLevel: 14, classOnly: 'elementalist', icon: 'almighty', desc: 'พลังบริสุทธิ์ถล่มศัตรูทั้งหมด', descEn: 'Pure power obliterates all enemies.' },
    { id: 'elemental_barrage', name: 'กระหน่ำจตุรธาตุ', nameEn: 'Elemental Barrage', element: 'fire', kind: 'attack', power: 1.3, cost: 19, target: 'singleEnemy', minLevel: 17, classOnly: 'elementalist', icon: 'sparkles', desc: 'ปล่อยธาตุสุ่มสามครั้งใส่ศัตรูเดี่ยว', descEn: 'Unleashes three random elemental strikes on a single enemy.', randomElement: ['fire', 'ice', 'elec', 'wind'], hits: 3 },
    { id: 'primal_spark', name: 'ประกายไฟปฐมภูมิ', nameEn: 'Primal Spark', element: 'fire', kind: 'attack', power: 1.3, cost: 5, target: 'singleEnemy', minLevel: 3, classOnly: 'elementalist', icon: 'fire', desc: 'ประกายไฟพื้นฐานพุ่งใส่ศัตรูเดี่ยว ต้นทุนต่ำ', descEn: 'A low-cost spark of primal fire strikes a single enemy.' },
    { id: 'elemental_cascade', name: 'ธาราธาตุถาโถม', nameEn: 'Elemental Cascade', element: 'fire', kind: 'attack', power: 1.15, cost: 18, target: 'allEnemies', minLevel: 11, classOnly: 'elementalist', icon: 'sparkles', desc: 'ปล่อยธาตุสุ่มใส่ศัตรูทั้งหมดพร้อมกัน', descEn: 'Unleashes a random element upon all enemies at once.', randomElement: ['fire', 'ice', 'elec', 'wind'] },

    // --- Cleric signatures ---
    { id: 'smite', name: 'อาญาสวรรค์', nameEn: 'Smite', element: 'light', kind: 'attack', power: 1.6, cost: 8, target: 'singleEnemy', minLevel: 1, classOnly: 'cleric', icon: 'radiantOrb', desc: 'พลังแสงลงทัณฑ์ศัตรูเดี่ยว', descEn: 'The power of light punishes a single enemy.' },
    { id: 'mark_of_sin', name: 'สาปมลทิน', nameEn: 'Mark of Sin', element: 'light', kind: 'debuffEnemy', stat: 'res', amount: 0.25, cost: 7, target: 'singleEnemy', minLevel: 5, classOnly: 'cleric', icon: 'debuffDown', desc: 'ตราบาปลดต้านเวทศัตรูเดี่ยว 25% ใน 3 เทิร์น', descEn: 'A mark of sin lowers a single enemy RES by 25% for 3 turns.' },
    { id: 'sanctuary', name: 'เขตคุ้มครอง', nameEn: 'Sanctuary', element: 'light', kind: 'buffSelf', stat: 'defres', amount: 0.35, cost: 14, target: 'self', minLevel: 8, classOnly: 'cleric', icon: 'shieldGuard', desc: 'เพิ่มการป้องกัน/ต้านเวท 35% ใน 3 เทิร์น พร้อมฟื้นฟู HP เล็กน้อย', descEn: 'Boosts DEF/RES by 35% for 3 turns and restores a small amount of HP.', healPower: 0.15 },
    { id: 'radiant_thunder', name: 'อสนีบาตแสง', nameEn: 'Radiant Thunder', element: 'light', kind: 'attack', power: 1.9, cost: 11, target: 'singleEnemy', minLevel: 11, classOnly: 'cleric', icon: 'light', desc: 'สายฟ้าศักดิ์สิทธิ์ฟาดใส่ศัตรูเดี่ยว', descEn: 'A holy thunderbolt strikes a single enemy.' },
    { id: 'judgment', name: 'วันพิพากษา', nameEn: 'Judgment', element: 'light', kind: 'attack', power: 1.2, cost: 20, target: 'allEnemies', minLevel: 16, classOnly: 'cleric', icon: 'light', desc: 'แสงพิพากษาศัตรูทั้งหมด', descEn: 'A light of judgment strikes all enemies.' },
    { id: 'angelic_ward', name: 'เกราะเทวะ', nameEn: 'Angelic Ward', element: 'light', kind: 'buffSelf', stat: 'defres', amount: 0.55, cost: 22, target: 'self', minLevel: 18, classOnly: 'cleric', icon: 'shieldGuard', desc: 'เพิ่มการป้องกัน/ต้านเวท 55% ใน 3 เทิร์น พร้อมฟื้นฟู HP ปานกลาง', descEn: 'Boosts DEF/RES by 55% for 3 turns and restores a moderate amount of HP.', healPower: 0.3 },
    { id: 'soothing_light', name: 'แสงบรรเทา', nameEn: 'Soothing Light', element: 'light', kind: 'heal', power: 0.25, cost: 5, target: 'self', minLevel: 3, classOnly: 'cleric', icon: 'heart', desc: 'ฟื้นฟู HP ราว 25% ของ HP สูงสุด ด้วยต้นทุนต่ำ', descEn: 'Restores about 25% of max HP at low cost.' },

    // --- Berserker signatures ---
    { id: 'reckless_strike', name: 'ฟาดเดือดดาล', nameEn: 'Reckless Strike', element: 'phys', kind: 'attack', power: 2.2, cost: 9, target: 'singleEnemy', minLevel: 1, classOnly: 'berserker', icon: 'swordAttack', desc: 'ฟันดะแบบไม่สนใจการป้องกันตัวเอง', descEn: 'A reckless swing that ignores self-preservation.' },
    { id: 'bloodlust', name: 'เลือดเดือด', nameEn: 'Bloodlust', element: 'phys', kind: 'buffSelf', stat: 'atk', amount: 0.35, cost: 8, target: 'self', minLevel: 5, classOnly: 'berserker', icon: 'buffUp', desc: 'เพิ่มพลังโจมตี 35% ใน 3 เทิร์น', descEn: 'Boosts ATK by 35% for 3 turns.' },
    { id: 'lifesteal_cleave', name: 'ดูดเลือดสังหาร', nameEn: 'Life-Steal Cleave', element: 'almighty', kind: 'attack', power: 1.6, cost: 10, target: 'singleEnemy', minLevel: 9, classOnly: 'berserker', icon: 'swordAttack', desc: 'ฟันสังหารด้วยแรงเดือดดาลที่ไม่มีสิ่งใดต้านทานได้ พร้อมดูดเลือดคืนชีวิต', descEn: 'A savage cleave of unstoppable rage that drains life from the wound.', drainSelf: true },
    { id: 'raging_whirl', name: 'พายุขวานเดือด', nameEn: 'Raging Whirl', element: 'phys', kind: 'attack', power: 1.35, cost: 18, target: 'allEnemies', minLevel: 11, classOnly: 'berserker', icon: 'swordAttack', desc: 'ขวานหมุนเดือดดาลฟาดศัตรูทั้งหมด', descEn: 'A furious spinning axe strikes all enemies.' },
    { id: 'berserks_end', name: 'จุดจบเดือดดาล', nameEn: "Berserker's End", element: 'phys', kind: 'attack', power: 2.8, cost: 20, target: 'singleEnemy', minLevel: 16, classOnly: 'berserker', icon: 'swordAttack', desc: 'ทุ่มสุดตัวครั้งสุดท้ายแบบไม่สนใจชีวิต', descEn: 'A final all-out assault with total disregard for self.' },
    { id: 'intimidating_roar', name: 'เสียงคำรามข่มขวัญ', nameEn: 'Intimidating Roar', element: 'phys', kind: 'debuffEnemy', stat: 'atk', amount: 0.2, cost: 5, target: 'singleEnemy', minLevel: 3, classOnly: 'berserker', icon: 'debuffDown', desc: 'เสียงคำรามข่มขวัญลดพลังโจมตีศัตรูเดี่ยว 20% ใน 3 เทิร์น', descEn: "A terrifying roar lowers a single enemy's ATK by 20% for 3 turns." },
    { id: 'bloodletting_axe', name: 'ขวานเลือดสาด', nameEn: 'Bloodletting Axe', element: 'phys', kind: 'attack', power: 2.3, cost: 14, target: 'singleEnemy', minLevel: 14, classOnly: 'berserker', icon: 'swordAttack', desc: 'ฟันขวานอย่างเดือดดาลจนเลือดสาด', descEn: 'A frenzied axe swing that draws blood.' },

    // --- Ranger signatures ---
    { id: 'piercing_shot', name: 'ธนูเจาะเกราะ', nameEn: 'Piercing Shot', element: 'phys', kind: 'attack', power: 1.9, cost: 7, target: 'singleEnemy', minLevel: 1, classOnly: 'ranger', icon: 'wind', desc: 'ลูกธนูความเร็วสูงเจาะเกราะศัตรู', descEn: "A high-speed arrow pierces the enemy's armor." },
    { id: 'hunters_focus', name: 'สมาธินักล่า', nameEn: "Hunter's Focus", element: 'wind', kind: 'buffSelf', stat: 'luk', amount: 0.4, cost: 7, target: 'self', minLevel: 5, classOnly: 'ranger', icon: 'buffUp', desc: 'เพิ่มโชค 40% ใน 3 เทิร์น เพิ่มโอกาสคริติคอล', descEn: 'Boosts LUK by 40% for 3 turns, raising crit chance.' },
    { id: 'binding_shot', name: 'ธนูพันธนาการ', nameEn: 'Binding Shot', element: 'phys', kind: 'debuffEnemy', stat: 'spd', amount: 0.3, cost: 6, target: 'singleEnemy', minLevel: 8, classOnly: 'ranger', icon: 'debuffDown', desc: 'ลูกธนูตรึงขาศัตรูเดี่ยว ลดความเร็ว 30% ใน 3 เทิร์น', descEn: "An arrow binds a single enemy's legs, lowering SPD by 30% for 3 turns." },
    { id: 'arrow_rain', name: 'ห่าฝนธนู', nameEn: 'Arrow Rain', element: 'wind', kind: 'attack', power: 1.15, cost: 15, target: 'allEnemies', minLevel: 11, classOnly: 'ranger', icon: 'wind', desc: 'ธนูตกลงมาเป็นสายฝนใส่ศัตรูทั้งหมด', descEn: 'A rain of arrows falls on all enemies.' },
    { id: 'perfect_shot', name: 'นัดสังหารเนรมิต', nameEn: 'Perfect Shot', element: 'phys', kind: 'attack', power: 2.5, cost: 16, target: 'singleEnemy', minLevel: 17, classOnly: 'ranger', icon: 'wind', desc: 'นัดยิงแม่นยำที่สุดในชีวิต เล็งจุดอ่อนสุดขีด', descEn: 'The single most precise shot of a lifetime, aimed at the deadliest point.' },
    { id: 'rapid_volley', name: 'ยิงรัวธนู', nameEn: 'Rapid Volley', element: 'phys', kind: 'attack', power: 1.4, cost: 5, target: 'singleEnemy', minLevel: 3, classOnly: 'ranger', icon: 'wind', desc: 'ยิงธนูรัวเร็วต้นทุนต่ำใส่ศัตรูเดี่ยว', descEn: 'A quick, low-cost volley of arrows hits a single enemy.' },
    { id: 'spirit_arrow', name: 'ธนูจิตวิญญาณ', nameEn: 'Spirit Arrow', element: 'wind', kind: 'attack', power: 2.2, cost: 14, target: 'singleEnemy', minLevel: 14, classOnly: 'ranger', icon: 'wind', desc: 'ธนูที่กลั่นจากจิตวิญญาณนักล่าพุ่งเจาะศัตรูเดี่ยว', descEn: "An arrow forged from the hunter's spirit pierces a single enemy." },

    // --- Necromancer signatures ---
    { id: 'curse_bolt', name: 'มนตร์สาปมืด', nameEn: 'Curse Bolt', element: 'dark', kind: 'attack', power: 1.6, cost: 8, target: 'singleEnemy', minLevel: 1, classOnly: 'necromancer', icon: 'dark', desc: 'พลังมืดสาปแช่งศัตรูเดี่ยว', descEn: 'A bolt of dark curse strikes a single enemy.' },
    { id: 'soul_siphon', name: 'ดูดวิญญาณ', nameEn: 'Soul Siphon', element: 'dark', kind: 'attack', power: 1.4, cost: 9, target: 'singleEnemy', minLevel: 5, classOnly: 'necromancer', icon: 'dark', desc: 'ดูดพลังวิญญาณศัตรูมาเยียวยาตนเอง', descEn: "Siphons the enemy's soul essence to heal yourself.", drainSelf: true },
    { id: 'withering_curse', name: 'คำสาปทำลายล้าง', nameEn: 'Withering Curse', element: 'dark', kind: 'debuffEnemy', stat: 'res', amount: 0.3, cost: 8, target: 'singleEnemy', minLevel: 9, classOnly: 'necromancer', icon: 'debuffDown', desc: 'คำสาปเซาะกร่อนต้านเวทศัตรูเดี่ยว 30% ใน 3 เทิร์น', descEn: "A withering curse erodes a single enemy's RES by 30% for 3 turns." },
    { id: 'grave_eruption', name: 'หลุมศพประทุ', nameEn: 'Grave Eruption', element: 'dark', kind: 'attack', power: 1.25, cost: 20, target: 'allEnemies', minLevel: 14, classOnly: 'necromancer', icon: 'dark', desc: 'วิญญาณจากหลุมศพระเบิดใส่ศัตรูทั้งหมด', descEn: 'Spirits erupt from the grave, striking all enemies.' },
    { id: 'cataclysm_damned', name: 'วิปโยคจากขุมนรก', nameEn: 'Cataclysm of the Damned', element: 'dark', kind: 'attack', power: 1.3, cost: 24, target: 'allEnemies', minLevel: 18, classOnly: 'necromancer', icon: 'dark', desc: 'เรียกวิญญาณผู้ถูกสาปทั้งหมดถล่มศัตรูทุกตัว', descEn: 'Summons the wailing damned to consume all enemies.' },
    { id: 'spirit_possession', name: 'จิตวิญญาณเข้าสิง', nameEn: 'Spirit Possession', element: 'dark', kind: 'buffSelf', stat: 'mag', amount: 0.2, cost: 5, target: 'self', minLevel: 3, classOnly: 'necromancer', icon: 'buffUp', desc: 'วิญญาณเข้าสิงเสริมพลังเวท 20% ใน 3 เทิร์น', descEn: 'A possessing spirit boosts MAG by 20% for 3 turns.' },
    { id: 'grave_horror', name: 'อสุรกายจากหลุมฝัง', nameEn: 'Grave Horror', element: 'dark', kind: 'attack', power: 2.3, cost: 14, target: 'singleEnemy', minLevel: 11, classOnly: 'necromancer', icon: 'dark', desc: 'เรียกอสุรกายจากหลุมฝังศพมาฉีกกระชากศัตรู', descEn: 'Summons a horror from the grave to savage the enemy.' },

    // --- Monk signatures ---
    { id: 'thunder_palm', name: 'ฝ่ามือสายฟ้า', nameEn: 'Thunder Palm', element: 'elec', kind: 'attack', power: 1.7, cost: 7, target: 'singleEnemy', minLevel: 1, classOnly: 'monk', icon: 'elec', desc: 'พลังกำปั้นชาร์จสายฟ้ากระแทกศัตรู', descEn: 'A palm strike charged with lightning slams the enemy.' },
    { id: 'weak_point_strike', name: 'จุดชี่อ่อนแอ', nameEn: 'Weak Point Strike', element: 'phys', kind: 'debuffEnemy', stat: 'def', amount: 0.25, cost: 6, target: 'singleEnemy', minLevel: 6, classOnly: 'monk', icon: 'debuffDown', desc: 'จุดจุดชี่อ่อนแอ ลดการป้องกันศัตรูเดี่ยว 25% ใน 3 เทิร์น', descEn: "Strikes a vital pressure point, lowering a single enemy's DEF by 25% for 3 turns." },
    { id: 'piercing_voltage', name: 'ประจุสายฟ้าทะลวง', nameEn: 'Piercing Voltage', element: 'elec', kind: 'attack', power: 2.0, cost: 12, target: 'singleEnemy', minLevel: 10, classOnly: 'monk', icon: 'elec', desc: 'ปล่อยกระแสไฟฟ้าทะลวงเข้าสู่ร่างศัตรู', descEn: "Channels a piercing voltage straight into the enemy's body." },
    { id: 'hundred_fists', name: 'ร้อยหมัดสายฟ้า', nameEn: 'Hundred Thunder Fists', element: 'elec', kind: 'attack', power: 1.3, cost: 17, target: 'allEnemies', minLevel: 12, classOnly: 'monk', icon: 'elec', desc: 'กระหน่ำหมัดสายฟ้าใส่ศัตรูทั้งหมด', descEn: 'A flurry of lightning-charged fists batters all enemies.' },
    { id: 'thousand_volt_fist', name: 'หมัดสายฟ้าล้างจักรวาล', nameEn: 'Thousand Volt Fist', element: 'elec', kind: 'attack', power: 1.3, cost: 20, target: 'singleEnemy', minLevel: 17, classOnly: 'monk', icon: 'elec', desc: 'ทุ่มหมัดสายฟ้าสุดพลังสองครั้งซ้อน', descEn: 'Unleashes two consecutive full-power lightning fists.', hits: 2 },
    { id: 'chi_step', name: 'ก้าวลมปราณ', nameEn: 'Chi Step', element: 'phys', kind: 'buffSelf', stat: 'spd', amount: 0.25, cost: 5, target: 'self', minLevel: 3, classOnly: 'monk', icon: 'buffUp', desc: 'ก้าวเบาดั่งลมปราณ เพิ่มความเร็ว 25% ใน 3 เทิร์น', descEn: 'A ki-infused step boosts SPD by 25% for 3 turns.' },
    { id: 'annihilating_fist', name: 'หมัดทำลายล้าง', nameEn: 'Annihilating Fist', element: 'elec', kind: 'attack', power: 2.2, cost: 14, target: 'singleEnemy', minLevel: 15, classOnly: 'monk', icon: 'elec', desc: 'หมัดชาร์จสายฟ้าเต็มพลังทำลายล้างศัตรูเดี่ยว', descEn: "A full-power, lightning-charged fist annihilates a single enemy." },

    // --- Paladin signatures ---
    { id: 'holy_strike', name: 'ฟันดาบศักดิ์สิทธิ์', nameEn: 'Holy Strike', element: 'phys', kind: 'attack', power: 1.6, cost: 8, target: 'singleEnemy', minLevel: 1, classOnly: 'paladin', icon: 'swordAttack', desc: 'ดาบชุบแสงศักดิ์สิทธิ์ฟันศัตรู', descEn: 'A blade blessed with holy light strikes the enemy.' },
    { id: 'holy_brand', name: 'ตราสัญลักษณ์ศักดิ์สิทธิ์', nameEn: 'Holy Brand', element: 'light', kind: 'debuffEnemy', stat: 'atk', amount: 0.25, cost: 7, target: 'singleEnemy', minLevel: 5, classOnly: 'paladin', icon: 'debuffDown', desc: 'ตราศักดิ์สิทธิ์ลดพลังโจมตีศัตรูเดี่ยว 25% ใน 3 เทิร์น', descEn: "A holy brand lowers a single enemy's ATK by 25% for 3 turns." },
    { id: 'divine_aegis', name: 'โล่แสงเทวะ', nameEn: 'Divine Aegis', element: 'light', kind: 'buffSelf', stat: 'defres', amount: 0.4, cost: 14, target: 'self', minLevel: 8, classOnly: 'paladin', icon: 'shieldGuard', desc: 'โล่แสงศักดิ์สิทธิ์เพิ่มการป้องกัน/ต้านเวท 40% ใน 3 เทิร์น', descEn: 'A holy light shield boosts DEF/RES by 40% for 3 turns.' },
    { id: 'sword_absolution', name: 'ดาบชำระบาป', nameEn: 'Sword of Absolution', element: 'phys', kind: 'attack', power: 2.0, cost: 13, target: 'singleEnemy', minLevel: 12, classOnly: 'paladin', icon: 'swordAttack', desc: 'ดาบแห่งการชำระล้างฟันศัตรูเดี่ยว', descEn: 'A sword of absolution cuts down a single enemy.' },
    { id: 'eternal_guardian', name: 'ผู้พิทักษ์นิรันดร์', nameEn: 'Eternal Guardian', element: 'light', kind: 'buffSelf', stat: 'defres', amount: 0.55, cost: 22, target: 'self', minLevel: 18, classOnly: 'paladin', icon: 'shieldGuard', desc: 'เพิ่มการป้องกัน/ต้านเวท 55% ใน 3 เทิร์น พร้อมฟื้นฟู HP ปานกลาง', descEn: 'Boosts DEF/RES by 55% for 3 turns and restores a moderate amount of HP.', healPower: 0.25 },
    { id: 'cleansing_light', name: 'แสงชำระบาป', nameEn: 'Cleansing Light', element: 'light', kind: 'heal', power: 0.25, cost: 6, target: 'self', minLevel: 3, classOnly: 'paladin', icon: 'heart', desc: 'ฟื้นฟู HP ราว 25% ของ HP สูงสุด ด้วยแสงศักดิ์สิทธิ์', descEn: 'Restores about 25% of max HP with holy light.' },
    { id: 'cross_of_judgment', name: 'กางเขนพิพากษา', nameEn: 'Cross of Judgment', element: 'light', kind: 'attack', power: 1.2, cost: 16, target: 'allEnemies', minLevel: 15, classOnly: 'paladin', icon: 'light', desc: 'แสงจากกางเขนศักดิ์สิทธิ์พิพากษาศัตรูทั้งหมด', descEn: 'Light from a holy cross judges all enemies.' },

    // --- Gunslinger signatures ---
    { id: 'quickdraw', name: 'ชักไวยิงไว', nameEn: 'Quickdraw Shot', element: 'phys', kind: 'attack', power: 1.9, cost: 7, target: 'singleEnemy', minLevel: 1, classOnly: 'gunslinger', icon: 'swordAttack', desc: 'ชักปืนยิงเร็วจี๋ใส่ศัตรูเดี่ยว', descEn: 'A lightning-fast draw fires at a single enemy.' },
    { id: 'steady_aim', name: 'เล็งนิ่ง', nameEn: 'Steady Aim', element: 'phys', kind: 'buffSelf', stat: 'luk', amount: 0.4, cost: 7, target: 'self', minLevel: 5, classOnly: 'gunslinger', icon: 'buffUp', desc: 'ตั้งสติเล็งนิ่ง เพิ่มโชค 40% ใน 3 เทิร์น เพิ่มโอกาสคริติคอล', descEn: 'Steadies the aim, boosting LUK by 40% for 3 turns and raising crit chance.' },
    { id: 'arcane_round', name: 'กระสุนเวทอาคม', nameEn: 'Arcane Round', element: 'elec', kind: 'attack', power: 2.0, cost: 12, target: 'singleEnemy', minLevel: 9, classOnly: 'gunslinger', icon: 'elec', desc: 'กระสุนชาร์จเวทอาคมเจาะทะลุศัตรูเดี่ยว', descEn: 'An arcane-charged round pierces a single enemy.' },
    { id: 'bullet_storm', name: 'พายุกระสุน', nameEn: 'Bullet Storm', element: 'phys', kind: 'attack', power: 1.15, cost: 16, target: 'allEnemies', minLevel: 12, classOnly: 'gunslinger', icon: 'swordAttack', desc: 'ระดมยิงกระสุนใส่ศัตรูทั้งหมด', descEn: 'Unleashes a hail of bullets on all enemies.' },
    { id: 'dead_mans_trigger', name: 'ไกปืนคนตาย', nameEn: "Dead Man's Trigger", element: 'phys', kind: 'attack', power: 2.5, cost: 17, target: 'singleEnemy', minLevel: 17, classOnly: 'gunslinger', icon: 'swordAttack', desc: 'นัดสุดท้ายที่เล็งไปยังจุดจบของศัตรู', descEn: "A final shot aimed at the enemy's end." },
    { id: 'kneecap_shot', name: 'ยิงข้อเข่า', nameEn: 'Kneecap Shot', element: 'phys', kind: 'debuffEnemy', stat: 'def', amount: 0.2, cost: 5, target: 'singleEnemy', minLevel: 3, classOnly: 'gunslinger', icon: 'debuffDown', desc: 'ยิงเจาะข้อเข่าลดการป้องกันศัตรูเดี่ยว 20% ใน 3 เทิร์น', descEn: "A shot to the knee lowers a single enemy's DEF by 20% for 3 turns." },
    { id: 'silver_round', name: 'กระสุนเงินพิเศษ', nameEn: 'Silver Round', element: 'elec', kind: 'attack', power: 2.2, cost: 14, target: 'singleEnemy', minLevel: 15, classOnly: 'gunslinger', icon: 'elec', desc: 'กระสุนพิเศษชาร์จเวทอาคมเต็มพลังเจาะศัตรูเดี่ยว', descEn: 'A special arcane-charged round pierces a single enemy at full power.' },

    // --- Druid signatures ---
    { id: 'thorn_whip', name: 'แส้เถาวัลย์หนาม', nameEn: 'Thorn Whip', element: 'wind', kind: 'attack', power: 1.6, cost: 8, target: 'singleEnemy', minLevel: 1, classOnly: 'druid', icon: 'wind', desc: 'เถาวัลย์หนามฟาดใส่ศัตรูเดี่ยว', descEn: 'A thorned vine lashes a single enemy.' },
    { id: 'withering_vines', name: 'เถาเหี่ยวเฉา', nameEn: 'Withering Vines', element: 'dark', kind: 'debuffEnemy', stat: 'def', amount: 0.25, cost: 7, target: 'singleEnemy', minLevel: 5, classOnly: 'druid', icon: 'debuffDown', desc: 'เถาวัลย์เหี่ยวเฉาลดการป้องกันศัตรูเดี่ยว 25% ใน 3 เทิร์น', descEn: "Withering vines lower a single enemy's DEF by 25% for 3 turns." },
    { id: 'natures_blessing', name: 'พรแห่งธรรมชาติ', nameEn: "Nature's Blessing", element: 'wind', kind: 'buffSelf', stat: 'defres', amount: 0.3, cost: 13, target: 'self', minLevel: 9, classOnly: 'druid', icon: 'shieldGuard', desc: 'พรธรรมชาติเพิ่มการป้องกัน/ต้านเวท 30% ใน 3 เทิร์น พร้อมฟื้นฟู HP เล็กน้อย', descEn: "Nature's blessing boosts DEF/RES by 30% for 3 turns and restores a small amount of HP.", healPower: 0.15 },
    { id: 'bramble_storm', name: 'พายุหนามพง', nameEn: 'Bramble Storm', element: 'wind', kind: 'attack', power: 1.15, cost: 16, target: 'allEnemies', minLevel: 12, classOnly: 'druid', icon: 'wind', desc: 'หนามพงพัดกระหน่ำศัตรูทั้งหมด', descEn: 'A storm of brambles batters all enemies.' },
    { id: 'wrath_of_wilds', name: 'พิโรธพงไพร', nameEn: 'Wrath of the Wilds', element: 'dark', kind: 'attack', power: 1.3, cost: 22, target: 'allEnemies', minLevel: 17, classOnly: 'druid', icon: 'dark', desc: 'พลังเสื่อมสลายจากพงไพรถล่มศัตรูทั้งหมด', descEn: 'The decaying wrath of the wilds crashes down on all enemies.' },
    { id: 'forests_vigor', name: 'พลังป่าใหญ่', nameEn: "Forest's Vigor", element: 'wind', kind: 'buffSelf', stat: 'mag', amount: 0.2, cost: 6, target: 'self', minLevel: 3, classOnly: 'druid', icon: 'buffUp', desc: 'พลังจากป่าใหญ่เสริมพลังเวท 20% ใน 3 เทิร์น', descEn: "The vigor of the great forest boosts MAG by 20% for 3 turns." },
    { id: 'wolfsbane_fang', name: 'เขี้ยวยาพิษหมาป่า', nameEn: 'Wolfsbane Fang', element: 'dark', kind: 'attack', power: 2.2, cost: 14, target: 'singleEnemy', minLevel: 15, classOnly: 'druid', icon: 'dark', desc: 'เขี้ยวชุบยาพิษจากพงไพรกัดใส่ศัตรูเดี่ยว', descEn: 'A fang laced with wolfsbane poison bites a single enemy.' },

    // --- Alchemist signatures ---
    { id: 'flame_flask', name: 'ขวดเพลิงปะทุ', nameEn: 'Flame Flask', element: 'fire', kind: 'attack', power: 1.5, cost: 8, target: 'singleEnemy', minLevel: 1, classOnly: 'alchemist', icon: 'fire', desc: 'ขว้างขวดเพลิงใส่ศัตรูเดี่ยว', descEn: 'Hurls a flask of flame at a single enemy.' },
    { id: 'toxic_flask', name: 'ขวดพิษกัดกร่อน', nameEn: 'Toxic Flask', element: 'dark', kind: 'debuffEnemy', stat: 'def', amount: 0.3, cost: 7, target: 'singleEnemy', minLevel: 5, classOnly: 'alchemist', icon: 'debuffDown', desc: 'ขวดยาพิษกัดกร่อนการป้องกันศัตรูเดี่ยว 30% ใน 3 เทิร์น', descEn: "A vial of corrosive poison lowers a single enemy's DEF by 30% for 3 turns." },
    { id: 'weakening_brew', name: 'ยาต้มบั่นทอน', nameEn: 'Weakening Brew', element: 'dark', kind: 'debuffEnemy', stat: 'res', amount: 0.25, cost: 8, target: 'singleEnemy', minLevel: 9, classOnly: 'alchemist', icon: 'debuffDown', desc: 'ยาต้มบั่นทอนลดต้านเวทศัตรูเดี่ยว 25% ใน 3 เทิร์น', descEn: "A weakening brew lowers a single enemy's RES by 25% for 3 turns." },
    { id: 'volatile_cocktail', name: 'ค็อกเทลเพลิงระเบิด', nameEn: 'Volatile Cocktail', element: 'fire', kind: 'attack', power: 1.15, cost: 16, target: 'allEnemies', minLevel: 12, classOnly: 'alchemist', icon: 'fire', desc: 'ค็อกเทลไฟระเบิดใส่ศัตรูทั้งหมด', descEn: 'A volatile cocktail explodes across all enemies.' },
    { id: 'grand_concoction', name: 'สูตรลับมหันตภัย', nameEn: 'Grand Concoction', element: 'dark', kind: 'attack', power: 1.3, cost: 22, target: 'allEnemies', minLevel: 17, classOnly: 'alchemist', icon: 'dark', desc: 'สูตรยาลับที่อันตรายที่สุดถล่มศัตรูทั้งหมด', descEn: 'The deadliest concoction ever brewed devastates all enemies.' },
    { id: 'empowering_elixir', name: 'น้ำยาเร่งพลัง', nameEn: 'Empowering Elixir', element: 'fire', kind: 'buffSelf', stat: 'mag', amount: 0.25, cost: 6, target: 'self', minLevel: 3, classOnly: 'alchemist', icon: 'buffUp', desc: 'ดื่มน้ำยาเร่งพลัง เพิ่มพลังเวท 25% ใน 3 เทิร์น', descEn: 'Drinking an empowering elixir boosts MAG by 25% for 3 turns.' },
    { id: 'concentrated_blast', name: 'ระเบิดเพลิงเข้มข้น', nameEn: 'Concentrated Blast', element: 'fire', kind: 'attack', power: 2.2, cost: 14, target: 'singleEnemy', minLevel: 15, classOnly: 'alchemist', icon: 'fire', desc: 'ขวดยาเข้มข้นระเบิดใส่ศัตรูเดี่ยวเต็มแรง', descEn: 'A concentrated flask detonates on a single enemy at full force.' },

    // --- Samurai signatures ---
    { id: 'iai_strike', name: 'ฟันสายฟ้าแลบ', nameEn: 'Iai Strike', element: 'phys', kind: 'attack', power: 2.1, cost: 9, target: 'singleEnemy', minLevel: 1, classOnly: 'samurai', icon: 'swordAttack', desc: 'ชักดาบฟันในพริบตาก่อนคู่ต่อสู้ตั้งตัวทัน', descEn: 'A blade drawn and struck faster than the eye can follow.' },
    { id: 'bushido_focus', name: 'จิตวิญญาณบูชิโด', nameEn: 'Bushido Focus', element: 'phys', kind: 'buffSelf', stat: 'atk', amount: 0.35, cost: 8, target: 'self', minLevel: 5, classOnly: 'samurai', icon: 'buffUp', desc: 'รวมจิตตามวิถีบูชิโด เพิ่มพลังโจมตี 35% ใน 3 เทิร์น', descEn: 'Channels the way of bushido, boosting ATK by 35% for 3 turns.' },
    { id: 'moonlit_slash', name: 'ฟันจันทร์เสี้ยว', nameEn: 'Moonlit Slash', element: 'almighty', kind: 'attack', power: 1.8, cost: 10, target: 'singleEnemy', minLevel: 9, classOnly: 'samurai', icon: 'swordAttack', desc: 'ท่าฟันภายใต้แสงจันทร์ที่แม่นยำถึงขีดสุด จนไม่มีเกราะหรือธาตุใดต้านทานได้', descEn: 'A moonlit cut of such perfect precision that no armor or element can resist it.' },
    { id: 'wind_wheel_slash', name: 'ฟันวงล้อสายลม', nameEn: 'Wind Wheel Slash', element: 'phys', kind: 'attack', power: 1.3, cost: 16, target: 'allEnemies', minLevel: 12, classOnly: 'samurai', icon: 'swordAttack', desc: 'หมุนดาบเป็นวงล้อสายลมฟาดศัตรูทั้งหมด', descEn: 'A whirling blade forms a wheel of wind, striking all enemies.' },
    { id: 'thousand_cherry_blossoms', name: 'พันกลีบซากุระ', nameEn: 'Thousand Cherry Blossoms', element: 'phys', kind: 'attack', power: 2.7, cost: 18, target: 'singleEnemy', minLevel: 17, classOnly: 'samurai', icon: 'swordAttack', desc: 'ท่าไม้ตายที่ฟันนับพันครั้งในเสี้ยววินาทีเดียว', descEn: 'A finishing technique of a thousand cuts in a single instant.' },
    { id: 'piercing_gaze', name: 'จ้องจับจุดอ่อน', nameEn: 'Piercing Gaze', element: 'phys', kind: 'debuffEnemy', stat: 'def', amount: 0.2, cost: 5, target: 'singleEnemy', minLevel: 3, classOnly: 'samurai', icon: 'debuffDown', desc: 'จับจ้องจุดอ่อนของศัตรู ลดการป้องกัน 20% ใน 3 เทิร์น', descEn: "A piercing gaze finds a weak point, lowering the enemy's DEF by 20% for 3 turns." },
    { id: 'twin_lightning_cut', name: 'ฟันสายฟ้าคู่', nameEn: 'Twin Lightning Cut', element: 'phys', kind: 'attack', power: 2.3, cost: 14, target: 'singleEnemy', minLevel: 15, classOnly: 'samurai', icon: 'swordAttack', desc: 'ฟันดาบสองครั้งเร็วราวสายฟ้าแลบ', descEn: 'Two blade strikes as fast as a lightning flash.' },

    // --- Warlock signatures ---
    { id: 'hex_bolt', name: 'มนตร์คำสาปมืด', nameEn: 'Hex Bolt', element: 'dark', kind: 'attack', power: 1.6, cost: 8, target: 'singleEnemy', minLevel: 1, classOnly: 'warlock', icon: 'dark', desc: 'พลังคำสาปมืดพุ่งใส่ศัตรูเดี่ยว', descEn: 'A bolt of dark hex strikes a single enemy.' },
    { id: 'infernal_pact', name: 'สัญญานรก', nameEn: 'Infernal Pact', element: 'fire', kind: 'debuffEnemy', stat: 'res', amount: 0.25, cost: 8, target: 'singleEnemy', minLevel: 5, classOnly: 'warlock', icon: 'debuffDown', desc: 'สัญญานรกเซาะกร่อนต้านเวทศัตรูเดี่ยว 25% ใน 3 เทิร์น', descEn: "An infernal pact erodes a single enemy's RES by 25% for 3 turns." },
    { id: 'soul_ember', name: 'ถ่านไฟวิญญาณ', nameEn: 'Soul Ember', element: 'fire', kind: 'attack', power: 1.5, cost: 9, target: 'singleEnemy', minLevel: 9, classOnly: 'warlock', icon: 'fire', desc: 'ถ่านไฟเผาผลาญวิญญาณศัตรูแล้วคืนพลังชีวิตให้ตัวเอง', descEn: "Burns the enemy's soul to ember, draining life back to the caster.", drainSelf: true },
    { id: 'demonic_covenant', name: 'พันธะปีศาจ', nameEn: 'Demonic Covenant', element: 'dark', kind: 'attack', power: 1.25, cost: 20, target: 'allEnemies', minLevel: 13, classOnly: 'warlock', icon: 'dark', desc: 'ปีศาจตามสัญญาโจมตีศัตรูทั้งหมด', descEn: 'Demons bound by the pact strike all enemies.' },
    { id: 'hellstorm_pact', name: 'สัญญาพายุนรก', nameEn: 'Hellstorm Pact', element: 'fire', kind: 'attack', power: 1.35, cost: 24, target: 'allEnemies', minLevel: 18, classOnly: 'warlock', icon: 'fire', desc: 'เรียกพายุเพลิงนรกถล่มศัตรูทั้งหมด', descEn: 'Summons a hellstorm of fire to consume all enemies.' },
    { id: 'blood_covenant', name: 'พันธะเลือด', nameEn: 'Blood Covenant', element: 'dark', kind: 'buffSelf', stat: 'mag', amount: 0.2, cost: 6, target: 'self', minLevel: 3, classOnly: 'warlock', icon: 'buffUp', desc: 'สัญญาเลือดกับปีศาจเสริมพลังเวท 20% ใน 3 เทิร์น', descEn: 'A blood covenant with a demon boosts MAG by 20% for 3 turns.' },
    { id: 'fiendish_soul_drain', name: 'ฉีกกระชากวิญญาณปีศาจ', nameEn: 'Fiendish Soul Rend', element: 'dark', kind: 'attack', power: 2.2, cost: 14, target: 'singleEnemy', minLevel: 15, classOnly: 'warlock', icon: 'dark', desc: 'ฉีกกระชากวิญญาณศัตรูด้วยความหิวโหยของปีศาจ', descEn: "Tears the enemy's soul apart with fiendish hunger." },

    // --- Battlemage signatures ---
    { id: 'rune_slash', name: 'ฟันอักขระสายฟ้า', nameEn: 'Rune Slash', element: 'phys', kind: 'attack', power: 1.8, cost: 8, target: 'singleEnemy', minLevel: 1, classOnly: 'battlemage', icon: 'swordAttack', desc: 'ดาบสลักอักขระสายฟ้าฟันศัตรูเดี่ยว', descEn: 'A blade etched with lightning runes cuts a single enemy.' },
    { id: 'arcane_edge', name: 'คมดาบเวท', nameEn: 'Arcane Edge', element: 'elec', kind: 'buffSelf', stat: 'atkmag', amount: 0.25, cost: 7, target: 'self', minLevel: 5, classOnly: 'battlemage', icon: 'buffUp', desc: 'ปลุกพลังเวทเข้าดาบ เพิ่มพลังโจมตี/เวท 25% ใน 3 เทิร์น', descEn: "Awakens the blade's arcane power, boosting ATK/MAG by 25% for 3 turns." },
    { id: 'thunder_brand', name: 'ตราสายฟ้าประทับ', nameEn: 'Thunder Brand', element: 'elec', kind: 'attack', power: 1.9, cost: 11, target: 'singleEnemy', minLevel: 9, classOnly: 'battlemage', icon: 'elec', desc: 'ตราสายฟ้าประทับลงบนศัตรูเดี่ยว', descEn: 'A brand of thunder is seared onto a single enemy.' },
    { id: 'runic_discharge', name: 'ปลดปล่อยอักขระ', nameEn: 'Runic Discharge', element: 'elec', kind: 'attack', power: 1.3, cost: 17, target: 'allEnemies', minLevel: 12, classOnly: 'battlemage', icon: 'elec', desc: 'อักขระบนดาบปลดปล่อยกระแสไฟฟ้าใส่ศัตรูทั้งหมด', descEn: "The blade's runes discharge lightning across all enemies." },
    { id: 'spellsword_finale', name: 'บทสรุปดาบเวท', nameEn: 'Spellsword Finale', element: 'phys', kind: 'attack', power: 2.6, cost: 18, target: 'singleEnemy', minLevel: 17, classOnly: 'battlemage', icon: 'swordAttack', desc: 'รวมพลังดาบและเวทลงในท่าไม้ตายเดียว', descEn: 'Fuses blade and spell into one final, decisive strike.' },
    { id: 'sundering_rune', name: 'อักขระทำลายเกราะ', nameEn: 'Sundering Rune', element: 'elec', kind: 'debuffEnemy', stat: 'def', amount: 0.2, cost: 5, target: 'singleEnemy', minLevel: 3, classOnly: 'battlemage', icon: 'debuffDown', desc: 'อักขระเวทสลายเกราะศัตรูเดี่ยว ลดการป้องกัน 20% ใน 3 เทิร์น', descEn: "A shattering rune lowers a single enemy's DEF by 20% for 3 turns." },
    { id: 'lightning_blade_strike', name: 'ดาบสายฟ้าฟาด', nameEn: 'Lightning Blade Strike', element: 'elec', kind: 'attack', power: 2.2, cost: 14, target: 'singleEnemy', minLevel: 15, classOnly: 'battlemage', icon: 'elec', desc: 'ดาบชาร์จสายฟ้าเต็มพลังฟาดใส่ศัตรูเดี่ยว', descEn: 'A fully lightning-charged blade strikes a single enemy.' },

    // --- Frost Oracle signatures ---
    { id: 'frost_vision', name: 'สายตาน้ำแข็ง', nameEn: 'Frost Vision', element: 'ice', kind: 'attack', power: 1.5, cost: 8, target: 'singleEnemy', minLevel: 1, classOnly: 'frostOracle', icon: 'ice', desc: 'สายตาทำนายเยือกเย็นแทงทะลุศัตรูเดี่ยว', descEn: 'A prophetic, freezing gaze pierces a single enemy.' },
    { id: 'chilling_omen', name: 'ลางร้ายเยือกแข็ง', nameEn: 'Chilling Omen', element: 'ice', kind: 'debuffEnemy', stat: 'def', amount: 0.25, cost: 7, target: 'singleEnemy', minLevel: 5, classOnly: 'frostOracle', icon: 'debuffDown', desc: 'ลางร้ายเยือกแข็งลดการป้องกันศัตรูเดี่ยว 25% ใน 3 เทิร์น', descEn: "A chilling omen lowers a single enemy's DEF by 25% for 3 turns." },
    { id: 'oracles_respite', name: 'ที่พักพิงผู้พยากรณ์', nameEn: "Oracle's Respite", element: 'light', kind: 'heal', power: 0.5, cost: 12, target: 'self', minLevel: 9, classOnly: 'frostOracle', icon: 'heart', desc: 'ฟื้นฟู HP ราว 50% ของ HP สูงสุด', descEn: 'Restores about 50% of max HP.' },
    { id: 'eternal_frost', name: 'น้ำแข็งนิรันดร์', nameEn: 'Eternal Frost', element: 'ice', kind: 'attack', power: 1.15, cost: 16, target: 'allEnemies', minLevel: 12, classOnly: 'frostOracle', icon: 'ice', desc: 'น้ำแข็งนิรันดร์แผ่ปกคลุมศัตรูทั้งหมด', descEn: 'Eternal frost blankets all enemies.' },
    { id: 'glacial_prophecy', name: 'คำพยากรณ์ธารน้ำแข็ง', nameEn: 'Glacial Prophecy', element: 'ice', kind: 'attack', power: 2.5, cost: 17, target: 'singleEnemy', minLevel: 17, classOnly: 'frostOracle', icon: 'ice', desc: 'คำพยากรณ์แช่แข็งชะตากรรมของศัตรู', descEn: "A prophecy of ice seals the enemy's fate." },
    { id: 'frost_ward', name: 'เกราะน้ำแข็ง', nameEn: 'Frost Ward', element: 'ice', kind: 'buffSelf', stat: 'res', amount: 0.25, cost: 6, target: 'self', minLevel: 3, classOnly: 'frostOracle', icon: 'shieldGuard', desc: 'เกราะน้ำแข็งห่อหุ้มกาย เพิ่มต้านเวท 25% ใน 3 เทิร์น', descEn: 'A ward of ice boosts RES by 25% for 3 turns.' },
    { id: 'prophetic_glacier', name: 'ธารน้ำแข็งพยากรณ์', nameEn: 'Prophetic Glacier', element: 'ice', kind: 'attack', power: 2.2, cost: 14, target: 'singleEnemy', minLevel: 15, classOnly: 'frostOracle', icon: 'ice', desc: 'ธารน้ำแข็งตามคำพยากรณ์ถาโถมใส่ศัตรูเดี่ยว', descEn: 'A prophesied glacier crashes down on a single enemy.' },

    // --- Storm Caller signatures ---
    { id: 'static_charge', name: 'ประจุไฟฟ้าสถิต', nameEn: 'Static Charge', element: 'elec', kind: 'attack', power: 1.6, cost: 8, target: 'singleEnemy', minLevel: 1, classOnly: 'stormCaller', icon: 'elec', desc: 'ประจุไฟฟ้าพุ่งใส่ศัตรูเดี่ยว', descEn: 'A charge of static electricity strikes a single enemy.' },
    { id: 'gathering_storm', name: 'พายุก่อตัว', nameEn: 'Gathering Storm', element: 'elec', kind: 'buffSelf', stat: 'mag', amount: 0.3, cost: 8, target: 'self', minLevel: 5, classOnly: 'stormCaller', icon: 'buffUp', desc: 'พายุก่อตัวรอบกาย เพิ่มพลังเวท 30% ใน 3 เทิร์น', descEn: 'A gathering storm swirls around the caster, boosting MAG by 30% for 3 turns.' },
    { id: 'tempest_lance', name: 'หอกพายุหมุน', nameEn: 'Tempest Lance', element: 'wind', kind: 'attack', power: 1.9, cost: 11, target: 'singleEnemy', minLevel: 9, classOnly: 'stormCaller', icon: 'wind', desc: 'หอกพายุหมุนเจาะทะลุศัตรูเดี่ยว', descEn: 'A lance of swirling tempest pierces a single enemy.' },
    { id: 'thunderhead', name: 'เมฆฝนฟ้าคะนอง', nameEn: 'Thunderhead', element: 'elec', kind: 'attack', power: 1.3, cost: 19, target: 'allEnemies', minLevel: 13, classOnly: 'stormCaller', icon: 'elec', desc: 'เมฆฝนฟ้าคะนองกระหน่ำศัตรูทั้งหมด', descEn: 'A towering thunderhead pounds all enemies.' },
    { id: 'eye_of_the_storm', name: 'ดวงตาพายุ', nameEn: 'Eye of the Storm', element: 'wind', kind: 'attack', power: 1.4, cost: 24, target: 'allEnemies', minLevel: 18, classOnly: 'stormCaller', icon: 'wind', desc: 'พายุใหญ่ที่สุดในชีวิตกวาดล้างศัตรูทั้งหมด', descEn: 'The greatest storm ever conjured obliterates all enemies.' },
    { id: 'static_discharge_curse', name: 'คำสาปประจุไฟฟ้า', nameEn: 'Static Discharge Curse', element: 'elec', kind: 'debuffEnemy', stat: 'res', amount: 0.2, cost: 6, target: 'singleEnemy', minLevel: 3, classOnly: 'stormCaller', icon: 'debuffDown', desc: 'ประจุไฟฟ้าสาปเซาะกร่อนต้านเวทศัตรูเดี่ยว 20% ใน 3 เทิร์น', descEn: "A cursed static charge erodes a single enemy's RES by 20% for 3 turns." },
    { id: 'heart_of_thunder', name: 'ใจกลางสายฟ้า', nameEn: 'Heart of Thunder', element: 'elec', kind: 'attack', power: 2.3, cost: 14, target: 'singleEnemy', minLevel: 15, classOnly: 'stormCaller', icon: 'elec', desc: 'สายฟ้าจากใจกลางพายุฟาดใส่ศัตรูเดี่ยว', descEn: 'Lightning from the heart of the storm strikes a single enemy.' },

    // --- Shadow Dancer signatures ---
    { id: 'shadow_step', name: 'ก้าวเงามืด', nameEn: 'Shadow Step', element: 'phys', kind: 'attack', power: 2.0, cost: 9, target: 'singleEnemy', minLevel: 1, classOnly: 'shadowDancer', icon: 'swordAttack', desc: 'ย่างก้าวผ่านเงามืดจู่โจมศัตรูเดี่ยว', descEn: 'Steps through the shadows to strike a single enemy.' },
    { id: 'veil_of_night', name: 'ม่านราตรี', nameEn: 'Veil of Night', element: 'dark', kind: 'buffSelf', stat: 'spd', amount: 0.4, cost: 7, target: 'self', minLevel: 5, classOnly: 'shadowDancer', icon: 'buffUp', desc: 'ม่านราตรีห่อหุ้มกาย เพิ่มความเร็ว 40% ใน 3 เทิร์น', descEn: 'A veil of night wraps the body, boosting SPD by 40% for 3 turns.' },
    { id: 'twin_fang_dance', name: 'ระบำเขี้ยวคู่', nameEn: 'Twin Fang Dance', element: 'dark', kind: 'attack', power: 1.5, cost: 10, target: 'singleEnemy', minLevel: 9, classOnly: 'shadowDancer', icon: 'dark', desc: 'เขี้ยวเงามืดสองเล่มกัดกินและดูดพลังชีวิตศัตรู', descEn: 'Twin shadow fangs tear into the enemy and drain their life.', drainSelf: true },
    { id: 'blade_of_a_thousand_shadows', name: 'ดาบพันเงา', nameEn: 'Blade of a Thousand Shadows', element: 'phys', kind: 'attack', power: 1.3, cost: 17, target: 'allEnemies', minLevel: 12, classOnly: 'shadowDancer', icon: 'swordAttack', desc: 'เงาซ้อนทับนับพันฟาดฟันศัตรูทั้งหมด', descEn: 'A thousand overlapping shadows cut down all enemies.' },
    { id: 'midnight_execution', name: 'ประหารยามเที่ยงคืน', nameEn: 'Midnight Execution', element: 'dark', kind: 'attack', power: 2.6, cost: 18, target: 'singleEnemy', minLevel: 17, classOnly: 'shadowDancer', icon: 'dark', desc: 'ท่าประหารที่จบชีวิตศัตรูในความมืดมิด', descEn: 'An execution technique that ends the enemy in absolute darkness.' },
    { id: 'whispering_fear', name: 'เสียงกระซิบสยองขวัญ', nameEn: 'Whispering Fear', element: 'dark', kind: 'debuffEnemy', stat: 'atk', amount: 0.2, cost: 5, target: 'singleEnemy', minLevel: 3, classOnly: 'shadowDancer', icon: 'debuffDown', desc: 'เสียงกระซิบจากเงามืดลดพลังโจมตีศัตรูเดี่ยว 20% ใน 3 เทิร์น', descEn: "A whisper from the shadows lowers a single enemy's ATK by 20% for 3 turns." },
    { id: 'nightblade_waltz', name: 'ระบำใบมีดราตรี', nameEn: 'Nightblade Waltz', element: 'dark', kind: 'attack', power: 2.3, cost: 14, target: 'singleEnemy', minLevel: 15, classOnly: 'shadowDancer', icon: 'dark', desc: 'ร่ายรำท่ามกลางเงามืดพร้อมฟันใบมีดหลายครั้ง', descEn: 'A dance through shadow, cutting with blades at every step.' },

    // --- Bard signatures ---
    { id: 'discordant_note', name: 'เสียงเพลงอสูร', nameEn: 'Discordant Note', element: 'wind', kind: 'attack', power: 1.4, cost: 7, target: 'singleEnemy', minLevel: 1, classOnly: 'bard', icon: 'wind', desc: 'เสียงเพลงแปร่งประสาทกระแทกศัตรูเดี่ยว', descEn: 'A jarring, discordant note strikes a single enemy.' },
    { id: 'song_of_valor', name: 'บทเพลงแห่งความกล้า', nameEn: 'Song of Valor', element: 'light', kind: 'buffSelf', stat: 'atkmag', amount: 0.25, cost: 7, target: 'self', minLevel: 5, classOnly: 'bard', icon: 'buffUp', desc: 'บทเพลงแห่งความกล้าเพิ่มพลังโจมตี/เวท 25% ใน 3 เทิร์น', descEn: 'A song of valor boosts ATK/MAG by 25% for 3 turns.' },
    { id: 'dirge_of_despair', name: 'บทเพลงอาลัยสิ้นหวัง', nameEn: 'Dirge of Despair', element: 'wind', kind: 'debuffEnemy', stat: 'atk', amount: 0.25, cost: 6, target: 'singleEnemy', minLevel: 8, classOnly: 'bard', icon: 'debuffDown', desc: 'บทเพลงอาลัยลดพลังโจมตีศัตรูเดี่ยว 25% ใน 3 เทิร์น', descEn: "A mournful dirge lowers a single enemy's ATK by 25% for 3 turns." },
    { id: 'anthem_of_rally', name: 'เพลงชุมนุมพลนักรบ', nameEn: 'Anthem of Rally', element: 'light', kind: 'buffSelf', stat: 'defres', amount: 0.35, cost: 14, target: 'self', minLevel: 12, classOnly: 'bard', icon: 'shieldGuard', desc: 'บทเพลงเรียกขวัญเพิ่มการป้องกัน/ต้านเวท 35% ใน 3 เทิร์น พร้อมฟื้นฟู HP เล็กน้อย', descEn: 'A rallying anthem boosts DEF/RES by 35% for 3 turns and restores a small amount of HP.', healPower: 0.15 },
    { id: 'finale_of_the_ages', name: 'บทอวสานแห่งยุคสมัย', nameEn: 'Finale of the Ages', element: 'light', kind: 'attack', power: 1.25, cost: 20, target: 'allEnemies', minLevel: 17, classOnly: 'bard', icon: 'light', desc: 'บทเพลงสุดท้ายที่ก้องกังวานไปทั่วสมรภูมิ', descEn: 'A final, resounding note echoes across the entire battlefield.' },
    { id: 'unnerving_melody', name: 'ทำนองสั่นประสาท', nameEn: 'Unnerving Melody', element: 'wind', kind: 'debuffEnemy', stat: 'res', amount: 0.2, cost: 5, target: 'singleEnemy', minLevel: 3, classOnly: 'bard', icon: 'debuffDown', desc: 'ทำนองสั่นประสาทลดต้านเวทศัตรูเดี่ยว 20% ใน 3 เทิร์น', descEn: "An unnerving melody lowers a single enemy's RES by 20% for 3 turns." },
    { id: 'piercing_refrain', name: 'บทซ้ำทิ่มแทง', nameEn: 'Piercing Refrain', element: 'wind', kind: 'attack', power: 2.0, cost: 13, target: 'singleEnemy', minLevel: 15, classOnly: 'bard', icon: 'wind', desc: 'โน้ตเพลงคมกริบทิ่มแทงศัตรูเดี่ยว', descEn: 'A sharp musical note pierces a single enemy.' },

    // --- Beastmaster signatures ---
    { id: 'fang_and_claw', name: 'เขี้ยวและกรงเล็บ', nameEn: 'Fang and Claw', element: 'phys', kind: 'attack', power: 1.9, cost: 8, target: 'singleEnemy', minLevel: 1, classOnly: 'beastmaster', icon: 'swordAttack', desc: 'โจมตีดุดันดั่งสัตว์ป่าใส่ศัตรูเดี่ยว', descEn: 'A savage, beast-like strike hits a single enemy.' },
    { id: 'primal_howl', name: 'เสียงคำรามดึกดำบรรพ์', nameEn: 'Primal Howl', element: 'phys', kind: 'buffSelf', stat: 'atk', amount: 0.35, cost: 8, target: 'self', minLevel: 5, classOnly: 'beastmaster', icon: 'buffUp', desc: 'เสียงคำรามปลุกสัญชาตญาณดิบ เพิ่มพลังโจมตี 35% ใน 3 เทิร์น', descEn: 'A primal howl awakens raw instinct, boosting ATK by 35% for 3 turns.' },
    { id: 'pouncing_gale', name: 'ตะปบสายลม', nameEn: 'Pouncing Gale', element: 'wind', kind: 'attack', power: 1.8, cost: 10, target: 'singleEnemy', minLevel: 9, classOnly: 'beastmaster', icon: 'wind', desc: 'พุ่งตะปบด้วยความเร็วดั่งสายลมใส่ศัตรูเดี่ยว', descEn: 'A wind-swift pounce strikes a single enemy.' },
    { id: 'feral_stampede', name: 'ฝูงสัตว์ป่าเหยียบกราด', nameEn: 'Feral Stampede', element: 'phys', kind: 'attack', power: 1.3, cost: 16, target: 'allEnemies', minLevel: 12, classOnly: 'beastmaster', icon: 'swordAttack', desc: 'ฝูงสัตว์ป่าพุ่งเหยียบกราดศัตรูทั้งหมด', descEn: 'A stampede of wild beasts tramples all enemies.' },
    { id: 'alpha_predators_strike', name: 'ท่าล่าจ่าฝูง', nameEn: "Alpha Predator's Strike", element: 'phys', kind: 'attack', power: 2.6, cost: 17, target: 'singleEnemy', minLevel: 17, classOnly: 'beastmaster', icon: 'swordAttack', desc: 'ท่าโจมตีของจ่าฝูงที่ไม่มีเหยื่อรายใดรอดพ้น', descEn: "The alpha's killing strike, from which no prey escapes." },
    { id: 'rending_bite', name: 'กัดฉีกเกราะ', nameEn: 'Rending Bite', element: 'phys', kind: 'debuffEnemy', stat: 'def', amount: 0.2, cost: 5, target: 'singleEnemy', minLevel: 3, classOnly: 'beastmaster', icon: 'debuffDown', desc: 'กัดฉีกเกราะศัตรูเดี่ยว ลดการป้องกัน 20% ใน 3 เทิร์น', descEn: "A rending bite lowers a single enemy's DEF by 20% for 3 turns." },
    { id: 'predators_instinct', name: 'สัญชาตญาณนักล่า', nameEn: "Predator's Instinct", element: 'wind', kind: 'attack', power: 2.3, cost: 14, target: 'singleEnemy', minLevel: 15, classOnly: 'beastmaster', icon: 'wind', desc: 'สัญชาตญาณดิบนำทางสู่จุดตายของศัตรูเดี่ยว', descEn: "Raw instinct guides the strike to a single enemy's vital point." },

    // --- Runeblade signatures ---
    { id: 'runic_edge', name: 'คมดาบอักขระมืด', nameEn: 'Runic Edge', element: 'phys', kind: 'attack', power: 1.6, cost: 8, target: 'singleEnemy', minLevel: 1, classOnly: 'runeblade', icon: 'swordAttack', desc: 'ดาบสลักอักขระมืดฟันศัตรูเดี่ยว', descEn: 'A blade etched with dark runes cuts a single enemy.' },
    { id: 'runic_ward', name: 'เกราะอักขระป้องกัน', nameEn: 'Runic Ward', element: 'dark', kind: 'buffSelf', stat: 'defres', amount: 0.3, cost: 7, target: 'self', minLevel: 5, classOnly: 'runeblade', icon: 'shieldGuard', desc: 'อักขระป้องกันเพิ่มการป้องกัน/ต้านเวท 30% ใน 3 เทิร์น', descEn: 'A protective rune boosts DEF/RES by 30% for 3 turns.' },
    { id: 'blood_rune_slash', name: 'ฟันอักขระเลือด', nameEn: 'Blood Rune Slash', element: 'dark', kind: 'attack', power: 1.9, cost: 10, target: 'singleEnemy', minLevel: 9, classOnly: 'runeblade', icon: 'dark', desc: 'อักขระเลือดบนดาบดูดพลังชีวิตจากบาดแผล', descEn: 'A blood rune on the blade siphons life from the wound.', drainSelf: true },
    { id: 'sigil_of_ruin', name: 'ตราแห่งความพินาศ', nameEn: 'Sigil of Ruin', element: 'dark', kind: 'attack', power: 1.25, cost: 18, target: 'allEnemies', minLevel: 13, classOnly: 'runeblade', icon: 'dark', desc: 'ตราแห่งความพินาศระเบิดใส่ศัตรูทั้งหมด', descEn: 'A sigil of ruin detonates across all enemies.' },
    { id: 'oathbreakers_judgment', name: 'คำพิพากษาผู้ผิดคำสัตย์', nameEn: "Oathbreaker's Judgment", element: 'phys', kind: 'attack', power: 2.7, cost: 19, target: 'singleEnemy', minLevel: 18, classOnly: 'runeblade', icon: 'swordAttack', desc: 'ท่าไม้ตายที่ตัดสินชะตากรรมศัตรูด้วยดาบและอักขระมืด', descEn: "A finishing blow that seals the enemy's fate with blade and dark rune." },
    { id: 'binding_sigil', name: 'อักขระผนึกพลัง', nameEn: 'Binding Sigil', element: 'dark', kind: 'debuffEnemy', stat: 'atk', amount: 0.2, cost: 5, target: 'singleEnemy', minLevel: 3, classOnly: 'runeblade', icon: 'debuffDown', desc: 'อักขระมืดผนึกพลังศัตรูเดี่ยว ลดพลังโจมตี 20% ใน 3 เทิร์น', descEn: "A dark sigil binds a single enemy's power, lowering ATK by 20% for 3 turns." },
    { id: 'shadow_verdict_blade', name: 'ดาบพิพากษาเงามืด', nameEn: 'Shadow Verdict Blade', element: 'dark', kind: 'attack', power: 2.3, cost: 14, target: 'singleEnemy', minLevel: 15, classOnly: 'runeblade', icon: 'dark', desc: 'ดาบอักขระมืดพิพากษาชะตากรรมศัตรูเดี่ยว', descEn: "A dark rune-blade delivers a verdict upon a single enemy." },

    // --- Sharpshooter signatures ---
    { id: 'aimed_shot', name: 'นัดเล็งแม่นยำ', nameEn: 'Aimed Shot', element: 'phys', kind: 'attack', power: 2.0, cost: 8, target: 'singleEnemy', minLevel: 1, classOnly: 'sharpshooter', icon: 'swordAttack', desc: 'นัดยิงเล็งแม่นยำใส่ศัตรูเดี่ยว', descEn: 'A carefully aimed shot hits a single enemy.' },
    { id: 'eagle_eye', name: 'สายตาอินทรี', nameEn: 'Eagle Eye', element: 'phys', kind: 'buffSelf', stat: 'luk', amount: 0.4, cost: 7, target: 'self', minLevel: 5, classOnly: 'sharpshooter', icon: 'buffUp', desc: 'สายตาคมกริบดั่งอินทรี เพิ่มโชค 40% ใน 3 เทิร์น เพิ่มโอกาสคริติคอล', descEn: "Eyes as sharp as an eagle's, boosting LUK by 40% for 3 turns and raising crit chance." },
    { id: 'crippling_shot', name: 'นัดยิงพิการ', nameEn: 'Crippling Shot', element: 'phys', kind: 'debuffEnemy', stat: 'def', amount: 0.3, cost: 8, target: 'singleEnemy', minLevel: 9, classOnly: 'sharpshooter', icon: 'debuffDown', desc: 'นัดยิงเจาะจุดอ่อนลดการป้องกันศัตรูเดี่ยว 30% ใน 3 เทิร์น', descEn: "A crippling shot lowers a single enemy's DEF by 30% for 3 turns." },
    { id: 'called_shot', name: 'นัดเล็งจุดตาย', nameEn: 'Called Shot', element: 'almighty', kind: 'attack', power: 1.6, cost: 10, target: 'singleEnemy', minLevel: 9, classOnly: 'sharpshooter', icon: 'swordAttack', desc: 'นัดยิงที่เล็งจุดตายจนไม่มีเกราะหรือธาตุใดต้านทานได้', descEn: "A shot aimed at a vital point that no armor or element can resist." },
    { id: 'suppressing_fire', name: 'ยิงกดดันวงกว้าง', nameEn: 'Suppressing Fire', element: 'phys', kind: 'attack', power: 1.15, cost: 16, target: 'allEnemies', minLevel: 12, classOnly: 'sharpshooter', icon: 'swordAttack', desc: 'กระหน่ำยิงกดดันศัตรูทั้งหมด', descEn: 'A hail of suppressing fire hits all enemies.' },
    { id: 'one_shot_one_kill', name: 'นัดเดียวจบ', nameEn: 'One Shot, One Kill', element: 'phys', kind: 'attack', power: 2.8, cost: 17, target: 'singleEnemy', minLevel: 17, classOnly: 'sharpshooter', icon: 'swordAttack', desc: 'นัดยิงที่แม่นยำที่สุดในชีวิต ไม่พลาดเป้าหมายแม้แต่น้อย', descEn: 'The single most precise shot of a lifetime, never missing its mark.' },
    { id: 'snap_shot', name: 'ยิงเบาไว', nameEn: 'Snap Shot', element: 'phys', kind: 'attack', power: 1.4, cost: 5, target: 'singleEnemy', minLevel: 3, classOnly: 'sharpshooter', icon: 'swordAttack', desc: 'นัดยิงเร็วต้นทุนต่ำใส่ศัตรูเดี่ยว', descEn: 'A quick, low-cost shot hits a single enemy.' },
    { id: 'heartseeker_round', name: 'กระสุนเจาะหัวใจ', nameEn: 'Heartseeker Round', element: 'phys', kind: 'attack', power: 2.3, cost: 14, target: 'singleEnemy', minLevel: 15, classOnly: 'sharpshooter', icon: 'swordAttack', desc: 'กระสุนที่เล็งตรงจุดสำคัญที่สุดของศัตรูเดี่ยว', descEn: "A round aimed straight at a single enemy's most vital point." },

    // --- Puppeteer signatures ---
    { id: 'marionette_strike', name: 'หุ่นเชิดจู่โจม', nameEn: 'Marionette Strike', element: 'dark', kind: 'attack', power: 1.5, cost: 8, target: 'singleEnemy', minLevel: 1, classOnly: 'puppeteer', icon: 'dark', desc: 'หุ่นเชิดเงามืดพุ่งเข้าจู่โจมศัตรูเดี่ยว', descEn: 'A shadow marionette lunges to strike a single enemy.' },
    { id: 'severed_strings', name: 'ตัดเส้นเอ็นบังคับ', nameEn: 'Severed Strings', element: 'dark', kind: 'debuffEnemy', stat: 'atk', amount: 0.25, cost: 7, target: 'singleEnemy', minLevel: 5, classOnly: 'puppeteer', icon: 'debuffDown', desc: 'ตัดเส้นเอ็นบังคับลดพลังโจมตีศัตรูเดี่ยว 25% ใน 3 เทิร์น', descEn: "Severing the enemy's strings lowers their ATK by 25% for 3 turns." },
    { id: 'puppet_shackles', name: 'โซ่ตรึงหุ่นกระบอก', nameEn: 'Puppet Shackles', element: 'dark', kind: 'debuffEnemy', stat: 'spd', amount: 0.3, cost: 8, target: 'singleEnemy', minLevel: 9, classOnly: 'puppeteer', icon: 'debuffDown', desc: 'โซ่ล่องหนตรึงศัตรูเดี่ยว ลดความเร็ว 30% ใน 3 เทิร์น', descEn: "Invisible strings bind a single enemy, lowering SPD by 30% for 3 turns." },
    { id: 'dance_of_marionettes', name: 'ระบำหุ่นเชิดเงา', nameEn: 'Dance of Marionettes', element: 'dark', kind: 'attack', power: 1.2, cost: 18, target: 'allEnemies', minLevel: 13, classOnly: 'puppeteer', icon: 'dark', desc: 'หุ่นเชิดเงาทั้งกองทัพร่ายรำถล่มศัตรูทั้งหมด', descEn: 'An army of shadow marionettes dances destruction across all enemies.' },
    { id: 'final_curtain_call', name: 'ม่านปิดฉากสุดท้าย', nameEn: 'Final Curtain Call', element: 'dark', kind: 'attack', power: 2.6, cost: 19, target: 'singleEnemy', minLevel: 18, classOnly: 'puppeteer', icon: 'dark', desc: 'ฉากสุดท้ายของการแสดงที่จบชีวิตศัตรู', descEn: "The final act of the show, ending the enemy's story." },
    { id: 'puppeteers_chant', name: 'บทสวดผู้บงการ', nameEn: "Puppeteer's Chant", element: 'dark', kind: 'buffSelf', stat: 'mag', amount: 0.2, cost: 6, target: 'self', minLevel: 3, classOnly: 'puppeteer', icon: 'buffUp', desc: 'บทสวดเรียกพลังเสริมพลังเวท 20% ใน 3 เทิร์น', descEn: "A summoning chant boosts MAG by 20% for 3 turns." },
    { id: 'demon_marionette', name: 'หุ่นเชิดปีศาจ', nameEn: 'Demon Marionette', element: 'dark', kind: 'attack', power: 2.2, cost: 14, target: 'singleEnemy', minLevel: 15, classOnly: 'puppeteer', icon: 'dark', desc: 'เรียกหุ่นเชิดปีศาจตนใหญ่เข้าจู่โจมศัตรูเดี่ยว', descEn: 'Summons a massive demon marionette to strike a single enemy.' },

    // --- Tempest Witch signatures ---
    { id: 'riptide_bolt', name: 'สายฟ้าคลื่นทะเล', nameEn: 'Riptide Bolt', element: 'ice', kind: 'attack', power: 1.6, cost: 8, target: 'singleEnemy', minLevel: 1, classOnly: 'tempestWitch', icon: 'ice', desc: 'คลื่นน้ำแข็งซัดใส่ศัตรูเดี่ยว', descEn: 'A bolt of icy riptide slams into a single enemy.' },
    { id: 'saltwater_curse', name: 'คำสาปน้ำเค็ม', nameEn: 'Saltwater Curse', element: 'ice', kind: 'debuffEnemy', stat: 'res', amount: 0.25, cost: 7, target: 'singleEnemy', minLevel: 5, classOnly: 'tempestWitch', icon: 'debuffDown', desc: 'คำสาปน้ำเค็มกัดกร่อนต้านเวทศัตรูเดี่ยว 25% ใน 3 เทิร์น', descEn: "A curse of brine erodes a single enemy's RES by 25% for 3 turns." },
    { id: 'maelstrom_focus', name: 'สมาธิวังวนทะเล', nameEn: 'Maelstrom Focus', element: 'elec', kind: 'buffSelf', stat: 'mag', amount: 0.3, cost: 9, target: 'self', minLevel: 9, classOnly: 'tempestWitch', icon: 'buffUp', desc: 'ดึงพลังวังวนทะเล เพิ่มพลังเวท 30% ใน 3 เทิร์น', descEn: "Draws upon the ocean's maelstrom, boosting MAG by 30% for 3 turns." },
    { id: 'storm_surge', name: 'คลื่นพายุซัดฝั่ง', nameEn: 'Storm Surge', element: 'elec', kind: 'attack', power: 1.2, cost: 18, target: 'allEnemies', minLevel: 12, classOnly: 'tempestWitch', icon: 'elec', desc: 'คลื่นพายุซัดสายฟ้าใส่ศัตรูทั้งหมด', descEn: 'A surging storm of lightning crashes over all enemies.' },
    { id: 'abyssal_tempest', name: 'พายุห้วงสมุทร', nameEn: 'Abyssal Tempest', element: 'ice', kind: 'attack', power: 1.35, cost: 23, target: 'allEnemies', minLevel: 17, classOnly: 'tempestWitch', icon: 'ice', desc: 'พายุจากห้วงสมุทรลึกที่สุดกลืนกินศัตรูทั้งหมด', descEn: 'A tempest from the deepest abyss consumes all enemies.' },
    { id: 'corroding_tide', name: 'คลื่นกัดกร่อน', nameEn: 'Corroding Tide', element: 'ice', kind: 'debuffEnemy', stat: 'def', amount: 0.2, cost: 6, target: 'singleEnemy', minLevel: 3, classOnly: 'tempestWitch', icon: 'debuffDown', desc: 'คลื่นน้ำเค็มกัดกร่อนการป้องกันศัตรูเดี่ยว 20% ใน 3 เทิร์น', descEn: "A corroding tide lowers a single enemy's DEF by 20% for 3 turns." },
    { id: 'abyssal_voltage', name: 'สายฟ้าใต้สมุทร', nameEn: 'Abyssal Voltage', element: 'elec', kind: 'attack', power: 2.2, cost: 14, target: 'singleEnemy', minLevel: 15, classOnly: 'tempestWitch', icon: 'elec', desc: 'สายฟ้าจากห้วงสมุทรลึกฟาดใส่ศัตรูเดี่ยว', descEn: 'Lightning from the deep abyss strikes a single enemy.' },

    // --- Chronomancer signatures ---
    { id: 'temporal_shard', name: 'เศษเวลาแตกกระจาย', nameEn: 'Temporal Shard', element: 'light', kind: 'attack', power: 1.6, cost: 7, target: 'singleEnemy', minLevel: 1, classOnly: 'chronomancer', icon: 'light', desc: 'เศษเสี้ยวเวลาแตกกระจายทิ่มแทงศัตรูเดี่ยว', descEn: 'A shattered fragment of time pierces a single enemy.' },
    { id: 'haste_field', name: 'สนามเร่งเวลา', nameEn: 'Haste Field', element: 'wind', kind: 'buffSelf', stat: 'spd', amount: 0.45, cost: 8, target: 'self', minLevel: 5, classOnly: 'chronomancer', icon: 'buffUp', desc: 'สนามบิดเวลาเร่งความเร็วตัวเอง 45% ใน 3 เทิร์น', descEn: 'A field of distorted time boosts SPD by 45% for 3 turns.' },
    { id: 'temporal_lock', name: 'ตรึงห้วงเวลา', nameEn: 'Temporal Lock', element: 'light', kind: 'debuffEnemy', stat: 'spd', amount: 0.3, cost: 8, target: 'singleEnemy', minLevel: 9, classOnly: 'chronomancer', icon: 'debuffDown', desc: 'ตรึงศัตรูเดี่ยวไว้ในห้วงเวลา ลดความเร็ว 30% ใน 3 เทิร์น', descEn: "Locks a single enemy within a stilled moment, lowering SPD by 30% for 3 turns." },
    { id: 'accelerated_moment', name: 'ห้วงขณะเร่งรัด', nameEn: 'Accelerated Moment', element: 'wind', kind: 'buffSelf', stat: 'atkmag', amount: 0.3, cost: 10, target: 'self', minLevel: 12, classOnly: 'chronomancer', icon: 'buffUp', desc: 'เร่งห้วงเวลารอบกาย เพิ่มพลังโจมตี/เวท 30% ใน 3 เทิร์น', descEn: 'Accelerates the moment around the caster, boosting ATK/MAG by 30% for 3 turns.' },
    { id: 'end_of_days', name: 'วาระสุดท้ายแห่งกาลเวลา', nameEn: 'End of Days', element: 'light', kind: 'attack', power: 1.3, cost: 21, target: 'allEnemies', minLevel: 17, classOnly: 'chronomancer', icon: 'light', desc: 'บิดเวลาทั้งหมดให้มาบรรจบ ณ วาระอวสานของศัตรู', descEn: "Bends all of time to converge on the enemies' final moment." },
    { id: 'temporal_fracture', name: 'รอยแตกกาลเวลา', nameEn: 'Temporal Fracture', element: 'light', kind: 'debuffEnemy', stat: 'res', amount: 0.2, cost: 5, target: 'singleEnemy', minLevel: 3, classOnly: 'chronomancer', icon: 'debuffDown', desc: 'รอยแตกในกาลเวลาลดต้านเวทศัตรูเดี่ยว 20% ใน 3 เทิร์น', descEn: "A fracture in time erodes a single enemy's RES by 20% for 3 turns." },
    { id: 'crushing_timeline', name: 'สายธารเวลาบดขยี้', nameEn: 'Crushing Timeline', element: 'light', kind: 'attack', power: 2.2, cost: 14, target: 'singleEnemy', minLevel: 15, classOnly: 'chronomancer', icon: 'light', desc: 'บีบอัดสายธารเวลาบดขยี้ศัตรูเดี่ยว', descEn: 'Compresses the timeline to crush a single enemy.' },

    // --- Valiant Warlord signatures (unlockable): warlords_decree is the only
    // allEnemies debuffEnemy skill in the game -- see battle-engine.js's
    // debuffEnemy branch. ---
    { id: 'warlord_cleave', name: 'ฟันสังหารจอมทัพ', nameEn: "Warlord's Cut", element: 'phys', kind: 'attack', power: 1.8, cost: 9, target: 'singleEnemy', minLevel: 1, classOnly: 'warlord', icon: 'swordAttack', desc: 'ฟันสังหารด้วยเกียรติแห่งจอมทัพใส่ศัตรูเดี่ยว', descEn: "A cut struck with a warlord's honor hits a single enemy." },
    { id: 'shatter_line', name: 'ทลายแนวรบ', nameEn: 'Break the Line', element: 'phys', kind: 'debuffEnemy', stat: 'def', amount: 0.25, cost: 6, target: 'singleEnemy', minLevel: 3, classOnly: 'warlord', icon: 'debuffDown', desc: 'ทลายแนวรบศัตรูเดี่ยว ลดการป้องกัน 25% ใน 3 เทิร์น', descEn: "Breaks a single enemy's line, lowering DEF by 25% for 3 turns." },
    { id: 'warlords_decree', name: 'ประกาศิตจอมทัพ', nameEn: "Warlord's Decree", element: 'phys', kind: 'debuffEnemy', stat: 'defres', amount: 0.22, cost: 16, target: 'allEnemies', minLevel: 8, classOnly: 'warlord', icon: 'debuffDown', desc: 'เสียงประกาศิตสั่นสะเทือนขวัญศัตรูทั้งหมด ลดการป้องกัน/ต้านเวททุกตัว 22% ใน 3 เทิร์น', descEn: "A commanding decree shakes every enemy's resolve, lowering DEF/RES by 22% for 3 turns." },
    { id: 'rallying_banner', name: 'ธงรวมพล', nameEn: 'Rallying Banner', element: 'phys', kind: 'buffSelf', stat: 'atkmag', amount: 0.3, cost: 10, target: 'self', minLevel: 11, classOnly: 'warlord', icon: 'buffUp', desc: 'ชูธงรวมพล เพิ่มพลังโจมตี/เวท 30% ใน 3 เทิร์น พร้อมฟื้นฟู HP เล็กน้อย', descEn: 'Raises a rallying banner, boosting ATK/MAG by 30% for 3 turns and restoring a small amount of HP.', healPower: 0.1 },
    { id: 'iron_wall_command', name: 'บัญชาปราการเหล็ก', nameEn: 'Iron Wall Command', element: 'phys', kind: 'buffSelf', stat: 'defres', amount: 0.4, cost: 12, target: 'self', minLevel: 15, classOnly: 'warlord', icon: 'shieldGuard', desc: 'บัญชาให้ตั้งปราการเหล็ก เพิ่มการป้องกัน/ต้านเวท 40% ใน 3 เทิร์น', descEn: 'Commands an iron wall stance, boosting DEF/RES by 40% for 3 turns.' },
    { id: 'final_march', name: 'การเดินทัพครั้งสุดท้าย', nameEn: 'Final March', element: 'phys', kind: 'attack', power: 1.3, cost: 20, target: 'allEnemies', minLevel: 18, classOnly: 'warlord', icon: 'swordAttack', desc: 'นำทัพบุกกวาดล้างศัตรูทั้งหมดในการเดินทัพครั้งสุดท้าย', descEn: 'Leads a final charge that sweeps across all enemies.' },

    // --- Valiant Shadowhunter signatures (unlockable): crippling_strike/
    // venom_mark/last_hunt use onHitDebuff, the only player skills in the
    // game that inflict a stat debuff as part of a successful attack.
    { id: 'crippling_strike', name: 'จู่โจมพิการ', nameEn: 'Crippling Strike', element: 'phys', kind: 'attack', power: 1.6, cost: 7, target: 'singleEnemy', minLevel: 1, classOnly: 'shadowhunter', icon: 'swordAttack', desc: 'จู่โจมจุดอ่อนใส่ศัตรูเดี่ยว บาดแผลลดความเร็วศัตรู 20% ใน 3 เทิร์น', descEn: "Strikes a single enemy's weak point; the wound lowers their SPD by 20% for 3 turns.", onHitDebuff: { stat: 'spd', amount: 0.2 } },
    { id: 'venom_mark', name: 'รอยแผลพิษ', nameEn: 'Venom Mark', element: 'dark', kind: 'attack', power: 1.5, cost: 8, target: 'singleEnemy', minLevel: 4, classOnly: 'shadowhunter', icon: 'dark', desc: 'ทิ้งรอยแผลพิษไว้บนศัตรูเดี่ยว ลดพลังโจมตี 20% ใน 3 เทิร์น', descEn: "Leaves a venomous mark on a single enemy, lowering their ATK by 20% for 3 turns.", onHitDebuff: { stat: 'atk', amount: 0.2 } },
    { id: 'shadow_binding_shot', name: 'นัดตรึงกาย', nameEn: 'Shadow Binding Shot', element: 'phys', kind: 'debuffEnemy', stat: 'spd', amount: 0.35, cost: 7, target: 'singleEnemy', minLevel: 7, classOnly: 'shadowhunter', icon: 'debuffDown', desc: 'นัดตรึงกายศัตรูเดี่ยว ลดความเร็ว 35% ใน 3 เทิร์น', descEn: "A binding shot lowers a single enemy's SPD by 35% for 3 turns." },
    { id: 'twin_shadow_fangs', name: 'เขี้ยวเงาคู่', nameEn: 'Twin Shadow Fangs', element: 'dark', kind: 'attack', power: 1.4, cost: 14, target: 'singleEnemy', minLevel: 11, classOnly: 'shadowhunter', icon: 'dark', desc: 'เขี้ยวเงามืดสองเล่มกัดใส่ศัตรูเดี่ยวติดต่อกัน', descEn: 'Twin shadow fangs tear into a single enemy in quick succession.', hits: 2 },
    { id: 'shadowhunters_focus', name: 'สมาธินักล่าเงา', nameEn: "Shadowhunter's Focus", element: 'wind', kind: 'buffSelf', stat: 'spd', amount: 0.5, cost: 9, target: 'self', minLevel: 14, classOnly: 'shadowhunter', icon: 'buffUp', desc: 'สมาธิของนักล่าเงาเพิ่มความเร็ว 50% ใน 3 เทิร์น', descEn: "The shadowhunter's focus boosts SPD by 50% for 3 turns." },
    { id: 'last_hunt', name: 'ล่าครั้งสุดท้าย', nameEn: 'Last Hunt', element: 'almighty', kind: 'attack', power: 2.4, cost: 18, target: 'singleEnemy', minLevel: 18, classOnly: 'shadowhunter', icon: 'almighty', desc: 'ท่าไม้ตายของนักล่าเงา ทิ้งบาดแผลลดการป้องกัน/ต้านเวทศัตรูเดี่ยว 30% ใน 3 เทิร์น', descEn: "The shadowhunter's finishing blow leaves a wound that lowers a single enemy's DEF/RES by 30% for 3 turns.", onHitDebuff: { stat: 'defres', amount: 0.3 } },

    // --- Valiant Executioner signatures (unlockable): reaping_slash/
    // coup_de_grace/thousand_cuts use executeThreshold+executeBonus, the
    // only player skills in the game whose power spikes against a low-HP target.
    { id: 'reaping_slash', name: 'เคียวเกี่ยวชีวิต', nameEn: 'Reaping Slash', element: 'phys', kind: 'attack', power: 1.7, cost: 9, target: 'singleEnemy', minLevel: 1, classOnly: 'executioner', icon: 'swordAttack', desc: 'ฟันเกี่ยวชีวิตศัตรูเดี่ยว พลังโจมตี +60% หากศัตรูเหลือ HP ต่ำกว่า 30%', descEn: "A reaping cut against a single enemy; power +60% if the target is below 30% HP.", executeThreshold: 0.3, executeBonus: 0.6 },
    { id: 'mark_for_death', name: 'ตราสังหาร', nameEn: 'Mark for Death', element: 'dark', kind: 'debuffEnemy', stat: 'res', amount: 0.3, cost: 6, target: 'singleEnemy', minLevel: 4, classOnly: 'executioner', icon: 'debuffDown', desc: 'ประทับตราสังหารศัตรูเดี่ยว ลดต้านเวท 30% ใน 3 เทิร์น', descEn: "Marks a single enemy for death, lowering RES by 30% for 3 turns." },
    { id: 'bloodlust_edge', name: 'คมกระหายเลือด', nameEn: 'Bloodlust Edge', element: 'dark', kind: 'attack', power: 1.6, cost: 10, target: 'singleEnemy', minLevel: 8, classOnly: 'executioner', icon: 'dark', desc: 'คมดาบกระหายเลือดฟันศัตรูเดี่ยวและดูดพลังชีวิตคืน', descEn: 'A bloodthirsty blade cuts a single enemy and drains life back.', drainSelf: true },
    { id: 'headhunters_gambit', name: 'เดิมพันนักล่าหัว', nameEn: "Headhunter's Gambit", element: 'phys', kind: 'buffSelf', stat: 'atk', amount: 0.4, cost: 9, target: 'self', minLevel: 11, classOnly: 'executioner', icon: 'buffUp', desc: 'เดิมพันทุ่มสุดตัว เพิ่มพลังโจมตี 40% ใน 3 เทิร์น', descEn: "An all-in gambit boosts ATK by 40% for 3 turns." },
    { id: 'coup_de_grace', name: 'ปลิดชีพเด็ดขาด', nameEn: 'Coup de Grâce', element: 'almighty', kind: 'attack', power: 1.9, cost: 16, target: 'singleEnemy', minLevel: 15, classOnly: 'executioner', icon: 'almighty', desc: 'ท่าปลิดชีพเด็ดขาดศัตรูเดี่ยว พลังโจมตี +100% หากศัตรูเหลือ HP ต่ำกว่า 35%', descEn: "A decisive finishing blow; power +100% if the target is below 35% HP.", executeThreshold: 0.35, executeBonus: 1.0 },
    { id: 'thousand_cuts', name: 'พันบาดแผล', nameEn: 'Thousand Cuts', element: 'phys', kind: 'attack', power: 1.4, cost: 22, target: 'singleEnemy', minLevel: 18, classOnly: 'executioner', icon: 'swordAttack', desc: 'สับฟันศัตรูเดี่ยวรัวๆ หลายครั้ง พลังโจมตี +50% หากศัตรูเหลือ HP ต่ำกว่า 40%', descEn: "A flurry of cuts against a single enemy; power +50% if the target is below 40% HP.", hits: 3, executeThreshold: 0.4, executeBonus: 0.5 },

    // --- Valiant Deathbringer signatures (unlockable): every signature
    // here pays with hpCost (a % of max HP) instead of MP -- the only class
    // in the game whose kit runs on a resource other than MP. See
    // battle-engine.js's hpCostAmt handling in playerAction.
    { id: 'blood_pact', name: 'สัญญาเลือด', nameEn: 'Blood Pact', element: 'dark', kind: 'attack', power: 2.0, cost: 0, target: 'singleEnemy', minLevel: 1, classOnly: 'deathbringer', icon: 'dark', desc: 'สังเวย HP ของตนเอง 8% แทน MP เพื่อทะลวงพลังใส่ศัตรูเดี่ยว', descEn: "Sacrifices 8% of the caster's own HP instead of MP to pierce a single enemy.", hpCost: 0.08 },
    { id: 'soul_harvest', name: 'เก็บเกี่ยววิญญาณ', nameEn: 'Soul Harvest', element: 'dark', kind: 'attack', power: 1.5, cost: 10, target: 'singleEnemy', minLevel: 4, classOnly: 'deathbringer', icon: 'dark', desc: 'เก็บเกี่ยววิญญาณศัตรูเดี่ยวมาเยียวยาตนเอง', descEn: "Harvests a single enemy's soul to heal the caster.", drainSelf: true },
    { id: 'crimson_seal', name: 'ตราแดงเลือด', nameEn: 'Crimson Seal', element: 'dark', kind: 'debuffEnemy', stat: 'res', amount: 0.3, cost: 8, target: 'singleEnemy', minLevel: 7, classOnly: 'deathbringer', icon: 'debuffDown', desc: 'ประทับตราแดงเลือดศัตรูเดี่ยว ลดต้านเวท 30% ใน 3 เทิร์น', descEn: "Seals a single enemy in crimson, lowering RES by 30% for 3 turns." },
    { id: 'dark_communion', name: 'พิธีกรรมมืด', nameEn: 'Dark Communion', element: 'dark', kind: 'buffSelf', stat: 'atkmag', amount: 0.35, cost: 0, target: 'self', minLevel: 11, classOnly: 'deathbringer', icon: 'buffUp', desc: 'สังเวย HP ของตนเอง 6% แทน MP เพื่อประกอบพิธีกรรมมืด เพิ่มพลังโจมตี/เวท 35% ใน 3 เทิร์น', descEn: "Sacrifices 6% of the caster's own HP instead of MP for a dark rite, boosting ATK/MAG by 35% for 3 turns.", hpCost: 0.06 },
    { id: 'oblivion_wave', name: 'คลื่นวิสัญญี', nameEn: 'Oblivion Wave', element: 'dark', kind: 'attack', power: 1.2, cost: 0, target: 'allEnemies', minLevel: 15, classOnly: 'deathbringer', icon: 'dark', desc: 'สังเวย HP ของตนเอง 12% แทน MP เพื่อปล่อยคลื่นวิสัญญีใส่ศัตรูทั้งหมด', descEn: "Sacrifices 12% of the caster's own HP instead of MP to unleash a wave of oblivion on all enemies.", hpCost: 0.12 },
    { id: 'apocalypse_of_ruin', name: 'วิบัติกาลอวสาน', nameEn: 'Apocalypse of Ruin', element: 'almighty', kind: 'attack', power: 2.8, cost: 0, target: 'singleEnemy', minLevel: 18, classOnly: 'deathbringer', icon: 'almighty', desc: 'สังเวย HP ของตนเอง 20% แทน MP เพื่อร่ายท่าไม้ตายทำลายล้างสูงสุดใส่ศัตรูเดี่ยว', descEn: "Sacrifices 20% of the caster's own HP instead of MP to unleash a maximally destructive finishing blow on a single enemy.", hpCost: 0.2 },

    // --- Valiant Vanguard signatures (unlockable): flowing_strike/
    // temporal_step/endless_assault use grantsBonusAp, the only player
    // skills in the game that refund their own action point on cast.
    { id: 'flowing_strike', name: 'ท่วงท่าไหลลื่น', nameEn: 'Flowing Strike', element: 'phys', kind: 'attack', power: 1.3, cost: 5, target: 'singleEnemy', minLevel: 1, classOnly: 'vanguard', icon: 'swordAttack', desc: 'ท่วงท่าไหลลื่นใส่ศัตรูเดี่ยว คืนพลังการกระทำทันทีเพื่อโจมตีต่อได้', descEn: 'A flowing strike against a single enemy that immediately refunds the action point, chaining into another action.', grantsBonusAp: true },
    { id: 'temporal_step', name: 'ก้าวข้ามเวลา', nameEn: 'Temporal Step', element: 'wind', kind: 'buffSelf', stat: 'spd', amount: 0.45, cost: 8, target: 'self', minLevel: 5, classOnly: 'vanguard', icon: 'buffUp', desc: 'ก้าวข้ามเวลาเพิ่มความเร็ว 45% ใน 3 เทิร์น โดยไม่เสียพลังการกระทำ', descEn: 'A step through time boosts SPD by 45% for 3 turns without spending the action point.', grantsBonusAp: true },
    { id: 'phantom_barrage', name: 'กระหน่ำเงาผี', nameEn: 'Phantom Barrage', element: 'wind', kind: 'attack', power: 1.4, cost: 13, target: 'singleEnemy', minLevel: 9, classOnly: 'vanguard', icon: 'wind', desc: 'กระหน่ำโจมตีดั่งเงาผีใส่ศัตรูเดี่ยวติดต่อกัน', descEn: 'A phantom barrage strikes a single enemy in quick succession.', hits: 2 },
    { id: 'vanguards_resolve', name: 'เจตจำนงหน่วยหน้า', nameEn: "Vanguard's Resolve", element: 'phys', kind: 'buffSelf', stat: 'defres', amount: 0.3, cost: 10, target: 'self', minLevel: 12, classOnly: 'vanguard', icon: 'shieldGuard', desc: 'เจตจำนงมั่นคงเพิ่มการป้องกัน/ต้านเวท 30% ใน 3 เทิร์น พร้อมฟื้นฟู HP เล็กน้อย', descEn: "Unshaken resolve boosts DEF/RES by 30% for 3 turns and restores a small amount of HP.", healPower: 0.15 },
    { id: 'endless_assault', name: 'โถมประจัญบานไม่สิ้นสุด', nameEn: 'Endless Assault', element: 'almighty', kind: 'attack', power: 1.6, cost: 11, target: 'singleEnemy', minLevel: 16, classOnly: 'vanguard', icon: 'almighty', desc: 'โหมโจมตีศัตรูเดี่ยวไม่หยุดยั้ง คืนพลังการกระทำทันทีเพื่อโจมตีต่อได้', descEn: 'A relentless assault on a single enemy that immediately refunds the action point, chaining into another action.', grantsBonusAp: true },
    { id: 'infinite_horizon', name: 'ขอบฟ้าไร้สิ้นสุด', nameEn: 'Infinite Horizon', element: 'wind', kind: 'attack', power: 1.35, cost: 18, target: 'allEnemies', minLevel: 18, classOnly: 'vanguard', icon: 'wind', desc: 'สายลมไร้สิ้นสุดกวาดล้างศัตรูทั้งหมด', descEn: 'A boundless gale sweeps across all enemies.' }
  ];

  // Purely physical classes: their kit is built around weapon damage, not
  // spellcasting, so they're barred from the shared elemental attack/heal
  // skills (fire_bolt, heal, etc.) that every other class can pick up.
  // Shared physical/utility skills (attack, focus, iron_stance, guard_break,
  // haste) and each class's own classOnly signatures are unaffected.
  var PHYSICAL_CLASSES = {
    blade: true,
    berserker: true,
    ranger: true,
    samurai: true,
    shadowDancer: true,
    beastmaster: true,
    sharpshooter: true,
    executioner: true
  };

  function isSharedMagicSkill(skill) {
    return skill.classOnly === null && skill.element !== 'phys' && (skill.kind === 'attack' || skill.kind === 'heal');
  }

  function isSkillAllowedForClass(skill, classId) {
    if (skill.classOnly !== null && skill.classOnly !== classId) return false;
    if (PHYSICAL_CLASSES[classId] && isSharedMagicSkill(skill)) return false;
    return true;
  }

  window.Game = window.Game || {};
  window.Game.Data = window.Game.Data || {};
  window.Game.Data.skills = skills;
  window.Game.Data.getSkill = function (id) {
    for (var i = 0; i < skills.length; i++) if (skills[i].id === id) return skills[i];
    return null;
  };
  window.Game.Data.isSkillAllowedForClass = isSkillAllowedForClass;
  window.Game.Data.getLearnedSkills = function (classId, level) {
    return skills.filter(function (s) {
      return isSkillAllowedForClass(s, classId) && s.minLevel <= level;
    });
  };
})();
